<?php $this->params = is_array($this->params) ? $this->params : [] ?>
<?php if ($this->pageCount): ?>
    <ul class="pagination">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li class="prev"><a href="<?= $this->url($this->route, $this->params, ['query' => ['page' => $this->previous]]); ?>"><i class="fa fa-chevron-left"></i></a></li>
        <?php else: ?>
            <li class="prev"><span class="disabled"><i class="fa fa-chevron-left"></i></span></li>
        <?php endif; ?>

        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li><a href="<?= $this->url($this->route, $this->params, ['query' => ['page' => $page]]); ?>"><?= $page; ?></a></li>
            <?php else: ?>
                <li class="active"><span><?= $page; ?></span></li>
            <?php endif; ?>
        <?php endforeach; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li class="next"><a href="<?= $this->url($this->route, $this->params, ['query' => ['page' => $this->next]]); ?>"><i class="fa fa-chevron-right"></i></a>
            </li>
        <?php else: ?>
            <li class="next"><span class="disabled"><i class="fa fa-chevron-right"></i></span></li>
        <?php endif; ?>
    </ul>
<?php endif; ?>