<?php
/**
 * @var \Contractor\Entity\ContractorCompany $company
 */
?>
    <div class="layout-toolbar">
        <div class="row middle-md">
            <div class="col-md">
                <h1><i class="fa fa-dashboard fa-fw"></i>
                    <?= $title = sprintf('%s: %s - %s', $this->translate('Dashboard'), $company->getContractorName(), $this->translate('Editing of purchase wagon data')) ?>
                </h1>
                <div class="hint"><?= $company->getContractorType() ?></div>
                <?php echo $this->headTitle($title) ?>
            </div>
            <div class="col-md end-md">
                <?= $this->partial('partial/dashboard-menu', ['company' => $company]) ?>
            </div>
        </div>
    </div>


<?php
/**
 * @var \Document\Domain\PurchaseContractEntity $contract
 * @var \Zend\Form\Element\Collection           $collection
 * @var \Zend\Form\Form                         $form
 * @var \Zend\Form\Fieldset                     $fieldset
 */
$form->setAttribute('action', $this->url('dashboard/purchaseWagon/edit', [
    'company'  => $company->getContractorId(),
    'contract' => $contract->getContractId()]));
$form->prepare();
echo $this->form()->openTag($form) ?>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

<?= $this->partial('document/purchase-contract/contract', ['contract' => $this->contract]); ?>

    <div class="row">
        <div class="col-md">

            <div class="panel">
                <div class="panel-header">
                    <div class="panel-title">
                        <i class="fa fa-tag fa-fw"></i>
                        <?= $this->translate('Common data') ?>
                    </div>
                </div>
                <div class="panel-body">
                    <?= $this->formHidden($form->get('csrf')) ?>
                    <?= $this->formHidden($form->get('wagon_id')) ?>

                    <div class="form-row">
                        <?= $this->formLabel($form->get('wagon_number')) ?>
                        <?= $this->formText($form->get('wagon_number')) ?>
                        <?= $this->formElementErrors($form->get('wagon_number')) ?>
                    </div>

                    <div class="form-row">
                        <?= $this->formLabel($form->get('loading_weight')) ?>
                        <?= $this->formNumber($form->get('loading_weight')) ?>
                        <?= $this->formElementErrors($form->get('loading_weight')) ?>
                    </div>


                    <div class="row">
                        <div class="col-md">
                            <div class="form-row">
                                <?= $this->formLabel($form->get('transport_price')) ?>
                                <?= $this->formNumber($form->get('transport_price')) ?>
                                <?= $this->formElementErrors($form->get('transport_price')) ?>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-row">
                                <?= $this->formLabel($form->get('transport_contractor_id')) ?>
                                <?= $this->formSelect($form->get('transport_contractor_id')) ?>
                                <?= $this->formElementErrors($form->get('transport_contractor_id')) ?>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <?= $this->formLabel($form->get('transport_comment')) ?>
                        <?= $this->formTextarea($form->get('transport_comment')) ?>
                        <?= $this->formElementErrors($form->get('transport_comment')) ?>
                    </div>
                </div>


            </div>

        </div>
        <div class="col-md-3">

            <div class="panel">
                <div class="panel-header">
                    <div class="panel-title">
                        <i class="fa fa-info-circle fa-fw"></i>
                        <?= $this->translate('Advanced data') ?>
                    </div>
                </div>
                <div class="panel-body">

                    <div class="form-row">
                        <?= $this->formLabel($form->get('loading_date')) ?>
                        <?= $this->formText($form->get('loading_date')) ?>
                        <?= $this->formElementErrors($form->get('loading_date')) ?>
                    </div>

                    <div id="carrierAndRate">

                        <div class="form-row">
                            <?= $this->formLabel($form->get('carrier_id')) ?>
                            <?= $this->formSelect($form->get('carrier_id')) ?>
                            <?= $this->formElementErrors($form->get('carrier_id')) ?>
                        </div>

                        <div class="form-row">
                            <?= $this->formLabel($form->get('rate_id')) ?>
                            <?= $this->formSelect($form->get('rate_id')) ?>
                            <?= $this->formElementErrors($form->get('rate_id')) ?>
                        </div>

                        <div class="form-row">
                            <?= $this->formLabel($form->get('rate_value_id')) ?>
                            <?= $this->formSelect($form->get('rate_value_id')) ?>
                            <?= $this->formElementErrors($form->get('rate_value_id')) ?>
                        </div>

                    </div>

                    <?= $this->formSubmit($form->get('save_and_exit')) ?>
                    <a href="<?= $this->url('dashboard/purchaseContract/advanced', ['company' => $company->getContractorId(), 'id' => $contract->getContractId()]) ?>"
                       class="btn btn-danger">
                        <i class="fa fa-close fa-fw"></i>
                        <?= $this->translate('Cancel') ?>
                    </a>

                </div>
            </div>

        </div>
    </div>

<?= $this->form()->closeTag() ?>

<?php
$this->headLink()->appendStylesheet('/css/datepicker.min.css');
$this->headLink()->appendStylesheet($this->basePath('/css/range-slider.css'));
$this->inlineScript()->appendFile($this->basePath('/js/vendor/datepicker.min.js'));
$this->inlineScript()->appendFile($this->basePath('/js/vendor/range-slider.min.js'));


$this->inlineScript()->captureStart();
echo /** @lang JavaScript */
<<<JS
$(document).ready(function () {
    
    if('carriagePaidTo' === '{$contract->getConditions()}') {
        $('.js-rate-value-id').hide();
        $('#carrierAndRate').hide();
    } else {
        $(document).on('change', 'input[name$="[loading_weight]"]', function() {
            //console.log($(this).closest('.row').find('select[name$="[rate_value_id]"] option'))
            var wv = $(this).val();
            $(this).closest('.row').find('select[name$="[rate_value_id]"] option').each(function(key, opt) {
                var min = $(opt).data('min'),
                    max = $(opt).data('max');
                if (min <= wv && max >= wv) {
                    $(opt).parent().val($(opt).attr('value'));
                    return false;
                }
            });
        });
    }

    $('input[name=loading_date]').datepicker({
        minDate : new Date({$contract->getCreated()->format('U')} * 1000),
        maxDate : new Date(),
        onSelect: function (formattedDate, date, inst) {
            inst.hide();
        }
    });

    var aSel = $('select[name=carrier_id]'),
        bSel = $('select[name=rate_id]'),
        cSel = $('select[name=rate_value_id]'),
        wNum = $('input[name=loading_weight]'),
        cBox = $('#carrierAndRate');

    $.ajax('/carrier/value-options', {
        data      : {
            carrier_type: '{$this->contract->getCarrierType()}',
            //country     : '{$this->contract->getCountry()}'
        },
        type      : 'post',
        success   : function (res) {
            aSel.empty();
            if (!res.length) return;
            $.each(res, function (key, obj) {
                $(document.createElement('option')).attr(obj.attributes).val(obj.value).text(obj.label).appendTo(aSel);
            }) && aSel.prop({
                disabled     : false,
                selectedIndex: 0
            }).val('{$form->getObject()->getCarrierId()}').change();
        },
        beforeSend: function () {
            aSel.closest('.panel-body').addClass('loading');
        },
        complete  : function () {
            setTimeout(function() {
                    aSel.closest('.panel-body').removeClass('loading');
            }, 1000);
        }
    });

    aSel.on('change', function () {
        bSel.prop('disabled', true);
        $.ajax('/rate/ajax-rates', {
            data      : {direction: 'inboundDirection', carrier: aSel.val()},
            type      : 'post',
            success   : function (res) {
                bSel.empty();
                if (!res.length) return;
                $.each(res, function (key, obj) {
                    $(document.createElement('option')).appendTo(bSel);
                    $(document.createElement('option')).attr(obj.attributes).val(obj.value).text(obj.label).appendTo(bSel);
                }) && bSel.prop({
                    disabled     : false,
                    selectedIndex: 0
                }).val('{$form->getObject()->getRateId()}').change();
            },
            beforeSend: function () {
                aSel.closest('.panel-body').addClass('loading');
            },
            complete  : function () {
                setTimeout(function() {
                    aSel.closest('.panel-body').removeClass('loading');
                }, 1000);
            }
        });
    });

    bSel.on('change', function () {
        cSel.prop('disabled', true);
        $.ajax('/rate/ajax-values', {
            data      : {rate: bSel.val()},
            type      : 'get',
            success   : function (res) {
                cSel.empty();
                if (!res.length) return;
                $.each(res, function (key, obj) {
                    $(document.createElement('option')).attr(obj.attributes).val(obj.value).text(obj.label).appendTo(cSel);
                }) && cSel.prop({
                    disabled     : false,
                    selectedIndex: 0
                }).val('{$form->getObject()->getRateValueId()}');
            },
            beforeSend: function () {
                bSel.closest('.panel-body').addClass('loading');
            },
            complete  : function () {
                setTimeout(function() {
                    bSel.closest('.panel-body').removeClass('loading');
                }, 1000);
            }
        });
    });

});
JS;
$this->inlineScript()->captureEnd() ?>