<?php

use Document\Domain\TransactionEntity;

if ($this->paginator->count()): ?>
    <table class="table-data">
        <thead>
        <tr>
            <th class="text-left"><?= $this->translate('Contractor') ?></th>
            <th class="text-right" style="width:10rem"><?= $this->translate('Debit') ?></th>
            <th class="text-right" style="width:10rem"><?= $this->translate('Credit') ?></th>
            <th class="text-center" style="width:15rem"><?= $this->translate('Operation type') ?></th>
            <th class="text-right" style="width:15rem"><?= $this->translate('Date') ?></th>
            <th class="text-right" style="width:5rem"><?= $this->translate('Tools') ?></th>
        </tr>
        </thead>
        <tbody>
        <?php /** @var ArrayObject $row */ ?>
        <?php foreach ($this->paginator as $row): ?>
            <tr>
                <td class="text-left"><?= $this->escapeHtml($row->offsetGet('contractor_name')) ?>
                    <div class="hint"><?= $this->escapeHtml($row->offsetGet('comment')) ?></div>
                </td>
                <td class="text-right"><?= $this->currencyFormat($row->offsetGet('debit')) ?></td>
                <td class="text-right"><?= $this->currencyFormat($row->offsetGet('credit')) ?></td>
                <td class="text-right text-center">
                    <?php if (TransactionEntity::TRANSACTION_DEBT === $row->offsetGet('transaction_type')): ?>
                        <div class="text-warning"><?= $this->translate('Debt') ?></div>
                    <?php elseif (TransactionEntity::TRANSACTION_PAYMENT === $row->offsetGet('transaction_type')): ?>
                        <div class="text-success"><?= $this->translate('Payment') ?></div>
                    <?php else: ?>
                        <div class="text-success"><?= $this->translate('Unsupported transaction type') ?></div>
                    <?php endif ?>

                </td>
                <td class="text-right">
                    <?= $this->dateFormat((new DateTime($row->offsetGet('created'))), IntlDateFormatter::MEDIUM, IntlDateFormatter::NONE) ?>
                    <div class="hint"><?= $this->dateFormat((new DateTime($row->offsetGet('created'))), IntlDateFormatter::NONE, IntlDateFormatter::LONG) ?></div>
                </td>
                <td class="text-right">
                    <?php if ($row->offsetGet('is_manual')): ?>
                        <div class="dropdown">
                            <button class="btn btn-default dropdown-toggle"><i class="fa fa-navicon"></i></button>
                            <ul class="dropdown-list">
                                <li><a href="<?= $this->url('transaction/carrier/edit', [
                                        'id' => $row->offsetGet('transaction_id')]) ?>"><i class="fa fa-pencil fa-fw"></i>
                                        <?= $this->translate('Edit transaction') ?></a></li>
                                <li>
                                    <a data-modal="confirm" href="<?= $this->url('transaction/carrier/delete', [
                                        'id' => $row->offsetGet('transaction_id')]) ?>"><i class="fa fa-trash fa-fw"></i>
                                        <?= $this->translate('Delete transaction') ?></a></li>
                            </ul>
                        </div>
                    <?php else: ?>
                        <button class="btn btn-default" disabled><i class="fa fa-navicon"></i></button>
                    <?php endif ?>
                </td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
<?php else: ?>
    <div class="text-center">
        <img src="<?= $this->basePath('img/empty.svg') ?>" alt="Empty folder" style="max-width:200px">
        <h3><?= $this->translate('Nothing found') ?></h3>
    </div>
<?php endif ?>
<script>
    $('.dropdown').dropdown();
    $('a[data-modal="confirm"]').modal({
        title      : '<?= $this->translate('Confirmation of deletion') ?>',
        message    : '<?= $this->translate('Are you sure you want to delete this entry?') ?>',
        cancelText : '<?= $this->translate('Cancel') ?>',
        confirmText: '<?= $this->translate('Confirm') ?>'
    });
</script>
