<div class="layout-toolbar">
    <div class="row middle-md">
        <div class="col-md">
            <h1>
                <i class="fa fa-users fa-fw"></i>
                <?= $title = $this->translate('Library: customers') ?>
            </h1>
            <?php echo $this->headTitle($title) ?>
        </div>
        <div class="col-md end-md">
            <div class="dropdown">
                <button class="dropdown-toggle btn btn-primary">
                    <i class="fa fa-plus-circle fa-fw"></i>
                    <?= $this->translate('Add new contractor') ?>
                </button>
                <ul class="dropdown-list">
                    <li>
                        <a href="<?= $this->url('contractorProvider/edit') ?>">
                            <i class="fa fa-download fa-fw"></i>
                            <?= $this->translate('Add new provider contractor') ?>
                        </a>
                    </li>
                    <li class="dropdown-list-separator"></li>
                    <li>
                        <a href="<?= $this->url('contractorCustomer/edit') ?>">
                            <i class="fa fa-upload fa-fw"></i>
                            <?= $this->translate('Add new customer contractor') ?>
                        </a>
                    </li>
                    <li class="dropdown-list-separator"></li>
                    <li>
                        <a href="<?= $this->url('contractorAdditional/edit') ?>">
                            <i class="fa fa-plus-circle fa-fw"></i>
                            <?= $this->translate('Add new additional contractor') ?>
                        </a>
                    </li>
                    <li class="dropdown-list-separator"></li>
                    <li>
                        <a href="<?= $this->url('contractorCorporate/edit') ?>">
                            <i class="fa fa-building fa-fw"></i>
                            <?= $this->translate('Add new corporate contractor') ?>
                        </a>
                    </li>
                    <li class="dropdown-list-separator"></li>
                    <li>
                        <a href="<?= $this->url('contractorCompany/edit') ?>">
                            <i class="fa fa-building fa-fw"></i>
                            <?= $this->translate('Add new company contractor') ?>
                        </a>
                    </li>
                    <li class="dropdown-list-separator"></li>
                    <li>
                        <a href="<?= $this->url('contractorPlant/edit') ?>">
                            <i class="fa fa-industry fa-fw"></i>
                            <?= $this->translate('Add new plant contractor') ?>
                        </a>
                    </li>
                    <li class="dropdown-list-separator"></li>
                    <li>
                        <a href="<?= $this->url('contractorConsignee/edit') ?>">
                            <i class="fa fa-inbox fa-fw"></i>
                            <?= $this->translate('Add new consignee contractor') ?>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

<?php /** @var \Zend\Paginator\Paginator $paginator */ ?>
<?php if ($paginator->count()): ?>

<div class="row">
    <div class="col-md">
        <div class="panel">
            <div class="panel-header">
                <div class="row middle-md">
                    <div class="col-md">
                        <div class="panel-title">
                            <i class="fa fa-navicon fa-fw"></i>
                            <?= $this->translate('Common contractor list') ?>
                        </div>
                    </div>
                    <div class="col-md end-md">
                        <?= $this->paginationControl($this->paginator, 'Sliding', 'partial/paginator', ['route' => 'contractorCommon']) ?>
                    </div>
                </div>
            </div>

            <div class="panel-body">
                <table class="table-data">
                    <thead>
                    <tr>
                        <th class="text-left"><?= $this->translate('Contractor name') ?></th>
                        <th class="text-center" style="width:7rem"><?= $this->translate('Register code') ?></th>
                        <th class="text-right" style="width:130px"><?= $this->translate('Updated') ?></th>
                        <th class="text-right" style="width:130px"><?= $this->translate('Created') ?></th>
                        <th class="text-right" style="width:48px"><?= $this->translate('Tools') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php /** @var \Contractor\Entity\ContractorAbstract $contractor */ ?>
                    <?php foreach ($this->paginator as $contractor): ?>
                        <?php
                        $routeEdit = sprintf('contractor%s/edit', ucwords($contractor->getContractorType()));
                        $routeDelete = sprintf('contractor%s/delete', ucwords($contractor->getContractorType()));
                        ?>
                        <tr>
                            <td class="text-left">
                                <a href="<?= $this->url($routeEdit, ['id' => $contractor->getContractorId()]) ?>">
                                    <?= $contractor->getContractorName() ?>
                                </a>
                                <div class="hint"><?= $contractor->getPerson()->toString() ?></div>
                            </td>
                            <td class="text-center"><?= $contractor->getRegisterCode() ?></td>
                            <td class="text-right"><?= $this->dateFormat($contractor->getUpdated(), IntlDateFormatter::LONG) ?>
                                <div class="hint"><?= $this->dateFormat($contractor->getUpdated(), IntlDateFormatter::NONE, IntlDateFormatter::LONG) ?></div>
                            </td>
                            <td class="text-right"><?= $this->dateFormat($contractor->getCreated(), IntlDateFormatter::LONG) ?>
                                <div class="hint"><?= $this->dateFormat($contractor->getCreated(), IntlDateFormatter::NONE, IntlDateFormatter::LONG) ?></div>
                            </td>
                            <td class="text-right">
                                <div class="dropdown">
                                    <button class="dropdown-toggle btn btn-default"><i class="fa fa-navicon"></i>
                                    </button>
                                    <ul class="dropdown-list">
                                        <li>
                                            <a href="<?= $this->url($routeEdit, ['id' => $contractor->getContractorId()]) ?>">
                                                <i class="fa fa-pencil fa-fw"></i>
                                                <?= $this->translate('Edit contractor') ?>
                                            </a>
                                        </li>
                                        <li class="dropdown-list-separator"></li>
                                        <li>
                                            <a href="<?= $this->url($routeDelete, ['id' => $contractor->getContractorId()]) ?>"
                                               data-modal="confirm">
                                                <i class="fa fa-trash fa-fw"></i><?= $this->translate('Delete contractor') ?>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>

        <?php else: ?>
            <div class="layout-not-found">
                <h3><?= $this->translate('No contractors') ?></h3>
            </div>
        <?php endif ?>
    </div>

    <div class="col-md-3">

        <div class="panel">
            <div class="panel-header">
                <div class="panel-title">
                    <i class="fa fa-filter fa-fw"></i>
                    <?= $this->translate('Filter') ?>
                </div>
            </div>
            <div class="panel-body">
                <?php
                /** @var \Zend\Form\Form $filterForm */
                $filterForm->prepare();
                $filterForm->setAttribute('action', $this->url('contractorCommon')) ?>
                <?= $this->form()->openTag($filterForm) ?>
                <div class="form-row">
                    <?= $this->formLabel($filterForm->get('contractor_type')) ?>
                    <?= $this->formSelect($filterForm->get('contractor_type')) ?>
                </div>
                <div class="form-row">
                    <?= $this->formLabel($filterForm->get('contractor_name')) ?>
                    <?= $this->formText($filterForm->get('contractor_name')) ?>
                </div>
                <div class="form-row">
                    <?= $this->formLabel($filterForm->get('register_code')) ?>
                    <?= $this->formText($filterForm->get('register_code')) ?>
                </div>
                <div class="form-row">
                    <div class="row">
                        <div class="col-md">
                            <?= $this->formSubmit($filterForm->get('filter')) ?>
                        </div>
                        <div class="col-md end-md">
                            <a class="btn btn-danger"
                               href="<?= $this->url('contractorCommon') ?>"><?= $this->translate('Reset filter') ?></a>
                        </div>
                    </div>
                </div>
                <?= $this->form()->closeTag() ?>
            </div>
        </div>
    </div>
</div>


<?php
$this->headLink()->appendStylesheet($this->basePath('css/dropdown.css'));
$this->inlineScript()->appendFile($this->basePath('js/dropdown.min.js'));
$this->headLink()->appendStylesheet($this->basePath('/css/modal.css'));
$this->inlineScript()->appendFile($this->basePath('/js/modal.js'));
$this->inlineScript()->captureStart();
echo /** @lang JavaScript */
<<<JS
$('.dropdown').dropdown();
$.modalConfig({
    title      : '{$this->translate('Confirmation of deletion')}',
    message    : '{$this->translate('Are you sure you want to delete this entry?')}',
    cancelText : '{$this->translate('Cancel')}',
    confirmText: '{$this->translate('Confirm')}'
});
JS;
$this->inlineScript()->captureEnd();
?>