<?php
/**
 * @var \Zend\Form\Element\Collection $collection
 * @var \Zend\Form\Form               $form
 * @var \Zend\Form\Fieldset           $fieldset
 */
$form->setAttribute('action', $this->url('furnace/loading', [], ['query' => ['company' => $this->companyId]]));
$form->prepare();
echo $this->form()->openTag($form) ?>

<div class="layout-toolbar">
    <div class="row middle-md">
        <div class="col-md">
            <h1>
                <i class="fa fa-pencil fa-fw"></i>
                <?= $title = $this->translate('Editing of furnace skip data') ?>
            </h1>
            <?php echo $this->headTitle($title) ?>
        </div>
        <div class="col-md end-md">
            <?= $this->formSubmit($form->get('start_producing')) ?>
            <a href="<?= $this->url('furnace') ?>" class="btn btn-danger">
                <i class="fa fa-close fa-fw"></i>
                <?= $this->translate('Cancel') ?>
            </a>
        </div>
    </div>
</div>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>


<?php if ($this->errorMessage): ?>
    <ul class="alert alert-error">
        <li><?= $this->translate($this->errorMessage) ?></li>
    </ul>
<?php endif ?>

<div class="panel">
    <div class="panel-header">
        <div class="panel-title">
            <i class="fa fa-tag fa-fw"></i>
            <?= $this->translate('Common data') ?>
        </div>
    </div>
    <div class="panel-body">
        <?= $this->formHidden($form->get('csrf')) ?>

        <div class="row">
            <div class="col-md">
                <div class="form-row">
                    <?= $this->formLabel($form->get('furnace_id')) ?>
                    <?= $this->formSelect($form->get('furnace_id')) ?>
                    <?= $this->formElementErrors($form->get('furnace_id')) ?>
                </div>
                <div class="form-row">
                    <?= $this->formLabel($form->get('date')) ?>
                    <?= $this->formText($form->get('date')) ?>
                    <?= $this->formElementErrors($form->get('date')) ?>
                </div>
            </div>
            <div class="col-md">
                <div class="form-row">
                    <?= $this->formLabel($form->get('material_warehouse_id')) ?>
                    <?= $this->formSelect($form->get('material_warehouse_id')) ?>
                    <?= $this->formElementErrors($form->get('material_warehouse_id')) ?>
                </div>
                <div class="form-row">
                    <?= $this->formLabel($form->get('product_warehouse_id')) ?>
                    <?= $this->formSelect($form->get('product_warehouse_id')) ?>
                    <?= $this->formElementErrors($form->get('product_warehouse_id')) ?>
                </div>
            </div>
        </div>


    </div>
</div>

<div class="panel">
    <div class="panel-header">
        <div class="panel-title">
            <i class="fa fa-tag fa-fw"></i>
            <?= $this->translate('Material data') ?>
        </div>
    </div>

    <div class="panel-body rower-section">
        <?php /** @var \Zend\Form\Element\Collection $collection */ ?>
        <?php $collection = $form->get('materials') ?>
        <?php /** @var \Zend\Form\Fieldset $fieldset */ ?>
        <?php foreach ($collection as $fieldset): ?>
            <div class="form-row">
                <div class="row">
                    <div class="col-lg">
                        <?= $this->formLabel($fieldset->get('provider_id')) ?>
                        <?= $this->formSelect($fieldset->get('provider_id')) ?>
                        <?= $this->formElementErrors($fieldset->get('provider_id')) ?>
                    </div>
                    <div class="col-lg">
                        <?= $this->formLabel($fieldset->get('material_id')) ?>
                        <?= $this->formSelect($fieldset->get('material_id')) ?>
                        <?= $this->formElementErrors($fieldset->get('material_id')) ?>
                    </div>
                    <div class="col-lg-1">
                        <?= $this->formLabel($fieldset->get('weight')) ?>
                        <?= $this->formNumber($fieldset->get('weight')) ?>
                        <?= $this->formElementErrors($fieldset->get('weight')) ?>
                    </div>
                    <div class="col-lg-1">
                        <?= $this->formLabel($fieldset->get('dropout')) ?>
                        <?= $this->formNumber($fieldset->get('dropout')) ?>
                        <?= $this->formElementErrors($fieldset->get('dropout')) ?>
                    </div>
                    <div class="col-lg-1"><br>
                        <?= $this->formButton($fieldset->get('remove')) ?>
                    </div>
                </div>
            </div>
        <?php endforeach ?>
        <!-- Email row template begin -->
        <script class="rower-template" type="text/html">
            <?php $template = $collection->getTemplateElement() ?>
            <div class="form-row">
                <div class="row">
                    <div class="col-lg">
                        <?= $this->formLabel($template->get('provider_id')) ?>
                        <?= $this->formSelect($template->get('provider_id')) ?>
                        <?= $this->formElementErrors($template->get('provider_id')) ?>
                    </div>
                    <div class="col-lg">
                        <?= $this->formLabel($template->get('material_id')) ?>
                        <?= $this->formSelect($template->get('material_id')->setAttribute('disabled', true)) ?>
                        <?= $this->formElementErrors($template->get('material_id')) ?>
                    </div>
                    <div class="col-lg-1">
                        <?= $this->formLabel($template->get('weight')) ?>
                        <?= $this->formNumber($template->get('weight')) ?>
                        <?= $this->formElementErrors($template->get('weight')) ?>
                    </div>
                    <div class="col-lg-1">
                        <?= $this->formLabel($template->get('dropout')) ?>
                        <?= $this->formNumber($template->get('dropout')) ?>
                        <?= $this->formElementErrors($template->get('dropout')) ?>
                    </div>
                    <div class="col-lg-1"><br>
                        <?= $this->formButton($template->get('remove')) ?>
                    </div>
                </div>
            </div>
        </script>
        <!-- Email row template end -->
    </div>

</div>

<?= $this->form()->closeTag() ?>

<?php
$this->headLink()->appendStylesheet('/css/datepicker.min.css');
$this->inlineScript()->appendFile($this->basePath('/js/vendor/datepicker.min.js'));
$this->inlineScript()->appendFile($this->basePath('/js/rower.min.js'));
$this->inlineScript()->captureStart();
echo <<<JS

$('input[name=date]').datepicker({maxDate: new Date(), onSelect: function(formattedDate, date, inst) { inst.hide(); }});

$('.rower-section').rower({
    addButtonClass  : 'btn btn-primary',
    rowSelector     : '.row',
    templateSelector: '.rower-template'
});

let changeVisibilityFields = function (element) {
    let supId     = $(element).val(),
        furPlantId = $('select[name=furnace_id]').find('option:checked').data('plant'),
        selMatId  = $(element).closest('.row').find('select[name$="[material_id]"]'),
        inWeight  = $(element).closest('.row').find('input[name$="[weight]"]'),
        inDropout = $(element).closest('.row').find('input[name$="[dropout]"]');
    selMatId.prop('selectedIndex', 0);
    console.log(supId.length)
    if (supId.length) {
        selMatId.find('option').hide().filter('option[data-provider=' + supId + '][data-plant='+furPlantId+']').show();
        selMatId.prop('disabled', false);
        inWeight.prop('disabled', false);
        inDropout.prop('disabled', false);
    } else {
        selMatId.prop('disabled', true);
        inWeight.prop('disabled', true);
        inDropout.prop('disabled', true);
    }
};

$(document).on('change', 'select[name$="[provider_id]"]', function() {
  changeVisibilityFields(this);
}).each(function() {
  changeVisibilityFields(this);
});

let changeVisibilityDropout = function(element) {
    let readonly = !$(element).find('option:checked').data('dropout');
    $(element).closest('.row').find('input[name$="[dropout]"]').prop('readonly', readonly).val(readonly ? 0 : 10);
    
};

$(document).on('change', 'select[name$="[material_id]"]', function() {
    changeVisibilityDropout(this);
}).each(function() {
  changeVisibilityDropout(this);
});

JS;
$this->inlineScript()->captureEnd() ?>
