<div class="layout-toolbar">
    <div class="row middle-md">
        <div class="col-md">
            <h1><i class="fa fa-pie-chart fa-fw"></i>&nbsp;<?= $title = $this->translate('Rates of dropout') ?></h1>
            <?php echo $this->headTitle($title) ?>
        </div>
        <div class="col-md end-md">
            <a href="<?= $this->url('dropout/edit') ?>" class="btn btn-primary">
                <i class="fa fa-plus-circle fa-fw"></i>
                <?= $this->translate('Add new rate of dropout') ?>
            </a>
        </div>
    </div>
</div>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

<?php /** @var \Zend\Paginator\Paginator $paginator */ ?>
<?php if ($paginator->count()): ?>

    <div class="panel">
        <div class="panel-header">
            <div class="row middle-md">
                <div class="col-md">
                    <div class="panel-title">
                        <i class="fa fa-navicon fa-fw"></i>
                        <?= $this->translate('Materials and dropout rates list') ?>
                    </div>
                </div>
                <div class="col-md end-md">
                    <?= $this->paginationControl($this->paginator, 'Sliding', 'partial/paginator', ['route' => 'dropout']) ?>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <table class="table-data">
                <thead>
                <tr>
                    <th class="text-left"><?= $this->translate('Provider name') ?></th>
                    <th class="text-left"><?= $this->translate('Material') ?></th>
                    <th class="text-center" style="width:4rem;"><?= $this->translate('Value') ?></th>
                    <th class="text-right" style="width:130px"><?= $this->translate('Period begin') ?></th>
                    <th class="text-right" style="width:130px"><?= $this->translate('Period end') ?></th>
                    <th class="text-right" style="width:48px"><?= $this->translate('Tools') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var \Dropout\Entity\DropoutEntity $dropout */ ?>
                <?php foreach ($this->paginator as $dropout): ?>
                    <tr>
                        <td class="text-left"><?= $dropout->getProviderName() ?></td>
                        <td class="text-left"><?= $dropout->getMaterialName() ?></td>
                        <td class="text-center"><?= $dropout->getValue() ?>%</td>
                        <td class="text-right"><?= $this->dateFormat($dropout->getPeriodBegin(), IntlDateFormatter::LONG) ?></td>
                        <td class="text-right"><?= $this->dateFormat($dropout->getPeriodEnd(), IntlDateFormatter::LONG) ?></td>
                        <td class="text-right">
                            <div class="dropdown">
                                <button class="dropdown-toggle btn btn-default"><i class="fa fa-navicon"></i></button>
                                <ul class="dropdown-list">
                                    <li>
                                        <a href="<?= $this->url('dropout/edit', ['id' => $dropout->getDropoutId()]) ?>">
                                            <i class="fa fa-pencil fa-fw"></i>
                                            <?= $this->translate('Edit rate') ?>
                                        </a>
                                    </li>
                                    <li class="dropdown-list-separator"></li>
                                    <li>
                                        <a href="<?= $this->url('dropout/delete', ['id' => $dropout->getDropoutId()]) ?>"
                                           data-modal="confirm">
                                            <i class="fa fa-trash fa-fw"></i>
                                            <?= $this->translate('Delete rate') ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>

<?php else: ?>
    <div class="layout-not-found">
        <h3><?= $this->translate('No drop-out rates') ?></h3>
        <p><?= $this->translate('Do you want to add a new rate of drop-out?') ?></p>
        <a href="<?= $this->url('dropout/edit') ?>" class="btn btn-lg btn-success">
            <i class="fa fa-plus-circle fa-fw"></i>
            <?= $this->translate('Add new rate of drop-out') ?>
        </a>
    </div>
<?php endif ?>


<?php
$this->headLink()->appendStylesheet($this->basePath('css/dropdown.css'));
$this->inlineScript()->appendFile($this->basePath('js/dropdown.min.js'));
$this->headLink()->appendStylesheet($this->basePath('/css/modal.css'));
$this->inlineScript()->appendFile($this->basePath('/js/modal.js'));
$this->inlineScript()->captureStart();
echo /** @lang JavaScript */
<<<JS
$('.dropdown').dropdown();
$.modalConfig({
    title      : '{$this->translate('Confirmation of deletion')}',
    message    : '{$this->translate('Are you sure you want to delete this entry?')}',
    cancelText : '{$this->translate('Cancel')}',
    confirmText: '{$this->translate('Confirm')}'
});
$(document).ready(function() {
    let form = $('#formDropoutFilter');
    form.on('submit', function(e) {
        e.preventDefault();
        window.location.search = '?' + $(this).find(':input').filter(function () {
                return $.trim(this.value).length > 0
            }).serialize();
    });
    
    let plantSelect   = $('select[name=plant_id]'),
        companySelect = $('select[name=company_id]').attr('disabled', true),
        companyFilter = function (plant, reset) {
            if (plant) {
                let options = companySelect.find('option').hide();
                options.filter('[data-plant=' + plant + ']').show();
                companySelect.removeAttr('disabled');
            } else {
                companySelect.attr('disabled', true)
            }
            if (reset) {
                companySelect.prop('selectedIndex', 0);
            }
        };
    plantSelect.on('change', function () {
        companyFilter(this.value, true);
    }).val() && companyFilter(plantSelect.val());
    
});
JS;
echo $this->inlineScript()->captureEnd();