<?php
/**
 * @var \Contractor\Entity\ContractorCompany $company
 */
?>
<div class="layout-toolbar">
    <div class="row middle-md">
        <div class="col-md">
            <h1><i class="fa fa-dashboard fa-fw"></i>
                <?= $title = sprintf('%s: %s - %s', $this->translate('Dashboard'), $company->getContractorName(), $this->translate('Editing of sale wagon data')) ?>
            </h1>
            <div class="hint"><?= $company->getContractorType() ?></div>
            <?php echo $this->headTitle($title) ?>
        </div>
        <div class="col-md end-md">
            <?= $this->partial('partial/dashboard-menu', ['company' => $company]) ?>
        </div>
    </div>
</div>


<?php
/**
 * @var \Document\Domain\PurchaseContractEntity $contract
 * @var \Zend\Form\Element\Collection $collection
 * @var \Zend\Form\Form $form
 * @var \Zend\Form\Fieldset $fieldset
 */
$form->setAttribute('action', $this->url('dashboard/saleWagon/loading', [
    'company'  => $company->getContractorId(),
    'contract' => $contract->getContractId()]));
$form->prepare();
echo $this->form()->openTag($form) ?>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

<?= $this->partial('document/sale-contract/contract', ['contract' => $this->contract]); ?>

<div class="row">
    <div class="col-md">

        <div class="panel">
            <div class="panel-header">
                <div class="panel-title">
                    <i class="fa fa-tag fa-fw"></i>
                    <?= $this->translate('Common data') ?>
                </div>
            </div>
            <div class="panel-body">
                <?= $this->formHidden($form->get('csrf')) ?>
                <?= $this->formHidden($form->get('wagon_id')) ?>

                <!-- Wagon collection begin -->
                <section class="rower-section">
                    <?php /** @var \Zend\Form\Element\Collection $collection */ ?>
                    <?php $collection = $form->get('wagons') ?>
                    <?php foreach ($collection as $fieldset): ?>
                        <div class="rower-row">
                            <div class="row start-md">
                                <?= $this->formHidden($fieldset->get('rate_id')) ?>
                                <div class="col-md-5">
                                    <div class="form-row">
                                        <?= $this->formText($fieldset->get('wagon_number')) ?>
                                        <?= $this->formElementErrors($fieldset->get('wagon_number')) ?>
                                    </div>
                                </div>
                                <div class="col-md">
                                    <div class="form-row">
                                        <?= $this->formNumber($fieldset->get('loading_weight')) ?>
                                        <?= $this->formElementErrors($fieldset->get('loading_weight')) ?>
                                    </div>
                                </div>
                                <div class="col-md js-rate-value-id">
                                    <div class="form-row">
                                        <?= $this->formSelect($fieldset->get('rate_value_id')) ?>
                                        <?= $this->formElementErrors($fieldset->get('rate_value_id')) ?>
                                    </div>
                                </div>
                                <div class="col-md-1">
                                    <div class="form-row">
                                        <?= $this->formButton($fieldset->get('remove')) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php endforeach ?>
                    <script class="rower-template" type="text/html">
                        <?php $template = $collection->getTemplateElement() ?>
                        <div class="rower-row">
                            <div class="row start-md">
                                <?= $this->formHidden($template->get('rate_id')) ?>
                                <div class="col-md-5">
                                    <div class="form-row">
                                        <?= $this->formText($template->get('wagon_number')) ?>
                                        <?= $this->formElementErrors($template->get('wagon_number')) ?>
                                    </div>
                                </div>
                                <div class="col-md">
                                    <div class="form-row">
                                        <?= $this->formNumber($template->get('loading_weight')) ?>
                                        <?= $this->formElementErrors($template->get('loading_weight')) ?>
                                    </div>
                                </div>
                                <div class="col-md">
                                    <div class="form-row js-rate-value-id">
                                        <?= $this->formSelect($template->get('rate_value_id')) ?>
                                        <?= $this->formElementErrors($template->get('rate_value_id')) ?>
                                    </div>
                                </div>
                                <div class="col-md-1">
                                    <div class="form-row">
                                        <?= $this->formButton($template->get('remove')) ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </script>
                </section>
                <!-- Wagon collection end -->

            </div>
        </div>

    </div>
    <div class="col-md-3">

        <div class="panel">
            <div class="panel-header">
                <div class="panel-title">
                    <i class="fa fa-info-circle fa-fw"></i>
                    <?= $this->translate('Advanced data') ?>
                </div>
            </div>
            <div class="panel-body">

                <div class="form-row">
                    <?= $this->formLabel($form->get('loading_date')) ?>
                    <?= $this->formText($form->get('loading_date')) ?>
                    <?= $this->formElementErrors($form->get('loading_date')) ?>
                </div>

                <div id="carrierAndRate">
                    <div class="form-row">
                        <?= $this->formLabel($form->get('carrier_id')) ?>
                        <?= $this->formSelect($form->get('carrier_id')) ?>
                        <?= $this->formElementErrors($form->get('carrier_id')) ?>
                    </div>

                    <div class="form-row">
                        <?= $this->formLabel($form->get('rate_id')) ?>
                        <?= $this->formSelect($form->get('rate_id')) ?>
                        <?= $this->formElementErrors($form->get('rate_id')) ?>
                    </div>

                </div>

                <?= $this->formSubmit($form->get('save_and_exit')) ?>
                <a href="<?= $this->url('dashboard/saleContract/advanced', ['company' => $company->getContractorId(), 'id' => $contract->getContractId()]) ?>"
                   class="btn btn-danger">
                    <i class="fa fa-close fa-fw"></i>
                    <?= $this->translate('Cancel') ?>
                </a>

            </div>
        </div>

    </div>
</div>

<?= $this->form()->closeTag() ?>

<?php
$this->headLink()->appendStylesheet('/css/datepicker.min.css');
$this->headLink()->appendStylesheet($this->basePath('/css/range-slider.css'));
$this->inlineScript()->appendFile($this->basePath('/js/rower.min.js'));
$this->inlineScript()->appendFile($this->basePath('/js/vendor/datepicker.min.js'));
$this->inlineScript()->appendFile($this->basePath('/js/vendor/range-slider.min.js'));


$this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function () {
    
    if('freeCarrier' === '{$contract->getConditions()}') {
        $('.js-rate-value-id').hide();
        $('#carrierAndRate').hide();
    } else {
        $(document).on('change', 'input[name$="[loading_weight]"]', function() {
            //console.log($(this).closest('.row').find('select[name$="[rate_value_id]"] option'))
            var wv = $(this).val();
            $(this).closest('.row').find('select[name$="[rate_value_id]"] option').each(function(key, opt) {
                var min = $(opt).data('min'),
                    max = $(opt).data('max');
                if (min <= wv && max >= wv) {
                    $(opt).parent().val($(opt).attr('value'));
                    return false;
                }
            });
        });
    }
    

    var dateObj = $('input[name=loading_date]').hide(),
        datePts = dateObj.val().split('.'),
        dpDate = dateObj.datepicker({
        minDate : new Date({$contract->getCreated()->format('U')} * 1000),
        maxDate : new Date(),
        inline: true,
        onSelect: function (formattedDate, date, inst) {
            inst.hide();
        }
    }).data('datepicker');
    
    if((datePts.length === 3)) {
        dpDate.selectDate(new Date(parseInt(datePts[2]), parseInt(datePts[1]) - 1, parseInt(datePts[0])));
    }
    

    var aSel = $('select[name=carrier_id]'),
        bSel = $('select[name=rate_id]'),
        
        cBox = $('#carrierAndRate');

    $.ajax('/carrier/value-options', {
        data      : {
            carrier_type: '{$this->contract->getCarrierType()}',
            //country     : '{$this->contract->getCountry()}',
            company     : '{$this->contract->getCompanyId()}'
        },
        type      : 'post',
        success   : function (res) {
            aSel.empty();
            if (!res.length) return;
            $.each(res, function (key, obj) {
                $(document.createElement('option')).attr(obj.attributes).val(obj.value).text(obj.label).appendTo(aSel);
            }) && aSel.prop({
                disabled     : false,
                selectedIndex: 0
            }).val('{$form->getObject()->getCarrierId()}').change();
        },
        beforeSend: function () {
            aSel.closest('.panel-body').addClass('loading');
        },
        complete  : function () {
            setTimeout(function () {
                aSel.closest('.panel-body').removeClass('loading');
            }, 1000);
        }
    });

    aSel.on('change', function () {
        bSel.prop('disabled', true);
        $.ajax('/rate/ajax-rates', {
            data      : {
                direction: 'outgoingDirection',
                carrier: aSel.val(),
                station: '{$contract->getStationId()}',
                period: true,
                company     : '{$this->contract->getCompanyId()}'
            },
            type      : 'post',
            success   : function (res) {
                bSel.empty();
                if (!res.length) return;
                $.each(res, function (key, obj) {
                    $(document.createElement('option')).attr(obj.attributes).val(obj.value).text(obj.label).appendTo(bSel);
                }) && bSel.prop({
                    disabled     : false,
                    selectedIndex: 0
                }).val('{$form->getObject()->getRateId()}');
            },
            beforeSend: function () {
                aSel.closest('.panel-body').addClass('loading');
            },
            complete  : function () {
                setTimeout(function () {
                    aSel.closest('.panel-body').removeClass('loading');
                }, 1000);
            }
        });
    });

    /*
    bSel.on('change', function () {
        var wNum   = $('input[name$="[loading_weight]"]'),
            rate   = $('input[name$="[rate_id]"]'),
            weight = $(this).find('option:selected').data('weight');
        if (0 <= weight.toString().indexOf('-'))
            weight = weight.split('-').map(parseFloat);
        wNum.attr({min: $.isArray(weight) ? weight[0] : weight, max: $.isArray(weight) ? weight[1] : weight});
        //wNum.val($.isArray(weight) ? weight.reduce((a, b) => a + b, 0) / 2 : weight);
        rate.val(this.value);
    });
    */
    
    bSel.on('change', function() {
        var cSel = $('select[name$="[rate_value_id]"]').empty();
        $.ajax('/rate/ajax-values', {
            data: {rate: this.value},
            type: 'get',
            success: function(res) {
                if (!res.length) return;
                cSel.empty() && $.each(res, function (key, obj) {
                    $(document.createElement('option')).attr(obj.attributes).val(obj.value).text(obj.label).appendTo(cSel);                    
                })
            }
        });
    });

    var fieldsetToggle = function () {
        var fset = $('.fieldset').not('[aria-expanded]'),
            body = fset.find('.fieldset-body'),
            show = !!body.find('input').filter(function () {
                return !!this.value && parseInt(this.value) !== 0;
            }).length || !!body.find('.form-errors').length;

        show && fset.attr('aria-expanded', 'true') || fset.attr('aria-expanded', 'false') && body.hide();

        fset.on('click', '.fieldset-toggle', function () {
            fset.attr('aria-expanded') === 'true' &&
            body.slideUp() && fset.attr('aria-expanded', 'false') ||
            body.slideDown() && fset.attr('aria-expanded', 'true');
        });
    };

    $('.rower-section').rower({
        addButtonClass  : 'btn btn-primary',
        rowSelector     : '.rower-row',
        templateSelector: '.rower-template',
        onInsert        : function (html) {
            fieldsetToggle();
            var weight = bSel.find('option:selected').data('weight'),
                curW   = html.find('input[name$="[loading_weight]"]'),
                curV   = html.find('select[name$="[rate_value_id]"]'),
                curR   = html.find('input[name$="[rate_id]"]');
            
            if (bSel.val()) {
                $.get('/rate/ajax-values', {rate: bSel.val()}, function(res) {
                    if (!res.length) return;
                    $.each(res, function (key, obj) {
                        $(document.createElement('option')).attr(obj.attributes).val(obj.value).text(obj.label).appendTo(curV);                    
                    });
                });
            }
            
            if (weight === undefined) return;
            if (0 <= weight.toString().indexOf('-')) weight = weight.split('-').map(parseFloat);
            curW.attr({min: $.isArray(weight) ? weight[0] : weight, max: $.isArray(weight) ? weight[1] : weight});
            //curW.val($.isArray(weight) ? weight.reduce((a, b) => a + b, 0) / 2 : weight);
            curW.val($.isArray(weight) ? weight[0] : weight);
            curR.val(bSel.val());
        }
    });

    $('.fieldset').each(function () {
        var fset = $(this),
            body = fset.find('.fieldset-body'),
            show = !!body.find('input').filter(function () {
                return !!this.value && parseInt(this.value) !== 0;
            }).length || !!body.find('.form-errors').length;

        show && fset.attr('aria-expanded', 'true') || fset.attr('aria-expanded', 'false') && body.hide();

        fset.on('click', '.fieldset-toggle', function () {
            fset.attr('aria-expanded') === 'true' &&
            body.slideUp() && fset.attr('aria-expanded', 'false') ||
            body.slideDown() && fset.attr('aria-expanded', 'true');
        });
    });

});
JS;
$this->inlineScript()->captureEnd() ?>
