<?php
/** @var \Zend\Form\Form $form */
$form->setAttribute('action', $this->url('tax/edit'));
$form->prepare();
echo $this->form()->openTag($form) ?>

    <div class="layout-toolbar">
        <div class="row middle-md">
            <div class="col-md">
                <h1>
                    <i class="fa fa-pencil fa-fw"></i>
                    <?= $title = $this->translate('Editing the tax') ?>
                </h1>
                <?php echo $this->headTitle($title) ?>
            </div>
            <div class="col-md end-md">
                <?= $this->formSubmit($form->get('save_and_remain')) ?>
                <?= $this->formSubmit($form->get('save_and_exit')) ?>
                <a href="<?= $this->url('tax') ?>" class="btn btn-danger">
                    <i class="fa fa-close fa-fw"></i>
                    <?= $this->translate('Cancel') ?>
                </a>
            </div>
        </div>
    </div>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

    <div class="panel">
        <div class="panel-header">
            <div class="panel-title">
                <i class="fa fa-tag fa-fw"></i>
                <?= $this->translate('Common data') ?>
            </div>
        </div>
        <div class="panel-body">
            <?= $this->formHidden($form->get('csrf')) ?>
            <?= $this->formHidden($form->get('tax_id')) ?>

            <div class="form-row">
                <?= $this->formLabel($form->get('tax_name')) ?>
                <?= $this->formText($form->get('tax_name')) ?>
                <?= $this->formElementErrors($form->get('tax_name')) ?>
            </div>

            <div class="form-row">
                <?= $this->formLabel($form->get('description')) ?>
                <?= $this->formTextarea($form->get('description')) ?>
                <?= $this->formElementErrors($form->get('description')) ?>
            </div>

            <div class="form-row">
                <?= $this->formLabel($form->get('value')) ?>
                <?= $this->formNumber($form->get('value')) ?>
                <?= $this->formElementErrors($form->get('value')) ?>
            </div>

        </div>
    </div>

<?= $this->form()->closeTag() ?>