<?php
/**
 * @var \Contractor\Entity\ContractorCompany $company
 * @var \Document\Domain\PurchaseContractEntity $contract
 * @var \Zend\Form\Element\Collection $collection
 * @var \Zend\Form\Form $form
 * @var \Zend\Form\Fieldset $fieldset
 */
?>
    <div class="layout-toolbar">
        <div class="row middle-md">
            <div class="col-md">
                <h1><i class="fa fa-download fa-fw"></i>
                    <?= $title = sprintf('%s - %s', $this->translate('Manage of purchase contract'), $company->getContractorName()) ?></h1>
                <?php echo $this->headTitle($title) ?>
            </div>
            <div class="col-md end-md">
                <?= $this->partial('partial/dashboard-menu', ['company' => $company]) ?>
            </div>
        </div>
    </div>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

    <div class="row">
        <div class="col-md">
            <div class="panel">
                <div class="panel-header">
                    <div class="row middle-md">
                        <div class="col-md-3">
                            <div class="panel-title">
                                <i class="fa fa-truck fa-fw"></i>
                                <?= $this->translate('Wagons data') ?>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <input type="text" id="unload-date" placeholder="<?= $this->translate('Unloading date') ?>"
                                   style="margin:0;height:28px;width:128px">
                            <a id="unload-selected" class="btn btn-primary btn-sm"
                               title="<?= $this->translate('Unloading wagons') ?>"
                               href="<?= $this->url('dashboard/purchaseWagon/unloading', [
                                   'company'  => $company->getContractorId(),
                                   'contract' => $contract->getContractId(),
                                   'id'       => 0]) ?>">
                                <i class="fa fa-upload fa-fw"></i></a>
                            <a id="delete-selected" class="btn btn-danger btn-sm"
                               title="<?= $this->translate('Delete wagons') ?>"
                               href="<?= $this->url('dashboard/purchaseWagon/delete', [
                                   'company'  => $company->getContractorId(),
                                   'contract' => $contract->getContractId(),
                                   'id'       => 0]) ?>">
                                <i class="fa fa-trash fa-fw"></i></a>
                        </div>
                        <div class="col-md-6 end-md">
                            <a class="btn btn-sm btn-primary" href="<?= $this->url('dashboard/purchaseWagon/import', [
                                'company'  => $company->getContractorId(),
                                'contract' => $this->contract->getContractId()]) ?>">
                                <i class="fa fa-upload fa-fw"></i>
                                <?= $this->translate('Import from Excel') ?>
                            </a>
                            <a class="btn btn-sm btn-primary" href="<?= $this->url('dashboard/purchaseWagon/export', [
                                'company'  => $company->getContractorId(),
                                'contract' => $this->contract->getContractId()], ['query' => $_GET]) ?>">
                                <i class="fa fa-download fa-fw"></i>
                                <?= $this->translate('Export to Excel') ?>
                            </a>
                            <a class="btn btn-sm btn-primary" href="<?= $this->url('dashboard/purchaseWagon/loading', [
                                'company'  => $company->getContractorId(),
                                'contract' => $this->contract->getContractId()]) ?>">
                                <i class="fa fa-plus-circle fa-fw"></i>
                                <?= $this->translate('Add new wagon') ?>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <?php /** @var \Zend\Form\Form $filterForm */
                    $filterForm = $this->filterForm;
                    $filterForm->setAttribute('action', $this->url('dashboard/purchaseContract/advanced', [], [], true));
                    $filterForm->setAttribute('method', 'get');
                    $filterForm->prepare();
                    echo $this->form()->openTag($filterForm);
                    echo $this->form()->closeTag() ?>
                    <table class="table-data">
                        <?php /** @var \Document\Domain\PurchaseWagonEntity $wagon */ ?>
                        <?php $this->placeholder('table_body')->captureStart() ?>
                        <?php if ($this->wagons && $this->wagons->count()): ?>
                            <tbody>
                            <?php foreach ($this->wagons as $wagon): ?>
                                <tr>
                                    <td><input type="checkbox" name="wagon[<?= $wagon->getWagonId() ?>]" data-id="<?= $wagon->getWagonId() ?>"></td>
                                    <td class="text-left">
                                        <?= $wagon->getWagonNumber() ?>
                                        <div class="hint"><?= $wagon->getCarrierName() ?></div>
                                    </td>
                                    <td class="text-center">
                                        <?php if ($wagon::STATUS_LOADED == $wagon->getStatus()): ?>
                                            <div class="text-warning"><?= $this->translate('Loaded') ?></div>
                                        <?php elseif ($wagon::STATUS_UNLOADED == $wagon->getStatus()): ?>
                                            <div class="text-success"><?= $this->translate('Unloaded') ?></div>
                                        <?php else: ?>
                                            <div class="text-error"><?= $this->translate('Status not defined') ?></div>
                                        <?php endif ?>
                                    </td>
                                    <td class="text-right">
                                        <?= $this->currencyFormat(bcadd($wagon->getMaterialPrice(), $wagon->getDeliveryPrice(), 2), 'UAH') ?>
                                        <div class="hint">
                                            <?= sprintf('%s / %s', $this->currencyFormat($wagon->getMaterialPrice(), 'UAH'), $this->currencyFormat($wagon->getDeliveryPrice(), 'UAH')) ?>
                                            <?php if (0 < $wagon->getTransportPrice()): ?>
                                                <i class="fa fa-info-circle fa-fw" title="<?= $wagon->getTransportComment() ?>"></i>
                                                <?= $this->currencyFormat($wagon->getTransportPrice()) ?>
                                            <?php endif ?>
                                        </div>
                                    </td>
                                    <td class="text-right">
                                        <?= $this->numberFormat($wagon->getLoadingWeight(), NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, null, 3, [
                                            NumberFormatter::POSITIVE_SUFFIX => sprintf(' %s.', $this->translate('tons'))]) ?>
                                        <div class="hint"><?= $this->dateFormat($wagon->getLoadingDate(), IntlDateFormatter::MEDIUM) ?></div>
                                    </td>
                                    <td class="text-right">
                                        <?php if ($wagon->getUnloadingDate() && $wagon->getUnloadingWeight()): ?>
                                            <?= $this->numberFormat($wagon->getUnloadingWeight(), NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, null, 3, [
                                                NumberFormatter::POSITIVE_SUFFIX => sprintf(' %s.', $this->translate('tons'))]) ?>
                                            <div class="hint"><?= $this->dateFormat($wagon->getUnloadingDate(), IntlDateFormatter::MEDIUM) ?></div>
                                        <?php else: ?>
                                            <div class="hint"><?= $this->translate('No specified') ?></div>
                                        <?php endif ?>
                                    </td>
                                    <td class="text-right">
                                        <div class="dropdown">
                                            <button class="dropdown-toggle btn btn-default"><i class="fa fa-navicon"></i>
                                            </button>
                                            <ul class="dropdown-list">
                                                <?php if ($wagon::STATUS_LOADED == $wagon->getStatus()): ?>
                                                    <li>
                                                        <a href="<?= $this->url('dashboard/purchaseWagon/unloading', [
                                                            'company'  => $company->getContractorId(),
                                                            'contract' => $wagon->getContractId(),
                                                            'id'       => $wagon->getWagonId()]) ?>">
                                                            <i class="fa fa-upload fa-fw"></i>
                                                            <?= $this->translate('Unloading wagon') ?>
                                                        </a>
                                                    </li>
                                                <?php endif; ?>
                                                <li>
                                                    <a href="<?= $this->url('dashboard/purchaseWagon/edit', [
                                                        'company'  => $company->getContractorId(),
                                                        'contract' => $wagon->getContractId(),
                                                        'id'       => $wagon->getWagonId()]) ?>">
                                                        <i class="fa fa-pencil fa-fw"></i>
                                                        <?= $this->translate('Edit wagon') ?>
                                                    </a>
                                                </li>
                                                <li class="dropdown-list-separator"></li>
                                                <li>
                                                    <a data-modal="confirm"
                                                       href="<?= $this->url('dashboard/purchaseWagon/delete', [
                                                           'company'  => $company->getContractorId(),
                                                           'contract' => $wagon->getContractId(),
                                                           'id'       => $wagon->getWagonId()]) ?>">
                                                        <i class="fa fa-trash fa-fw"></i>
                                                        <?= $this->translate('Delete wagon') ?>
                                                    </a>
                                                </li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                            <?php endforeach ?>
                            </tbody>
                        <?php endif ?>
                        <?php $this->placeholder('table_body')->captureEnd() ?>
                        <thead>
                        <tr>
                            <th class="text-center" style="width:1.5rem"><input type="checkbox" name="wagon_all"></th>
                            <th class="text-left"><?= sprintf('%s / %s', $this->translate('Wagon number'), $this->translate('Carrier')) ?></th>
                            <th class="text-center" style="width:7rem"><?= $this->translate('Wagon status') ?></th>
                            <th class="text-right"><?= sprintf('%s / %s', $this->translate('Material'), $this->translate('Transport')) ?></th>
                            <th class="text-right"
                                style="width:10rem"><?= sprintf('%s / %s', $this->translate('Loading weight'), $this->translate('date')) ?></th>
                            <th class="text-right"
                                style="width:10rem"><?= sprintf('%s / %s', $this->translate('Unloading weight'), $this->translate('date')) ?></th>
                            <th class="text-right" style="width:6rem"><?= $this->translate('Tools') ?></th>
                        </tr>
                        <tr>
                            <td>&nbsp;</td>
                            <td>
                                <div class="row" style="max-width:280px">
                                    <div class="col-md-4">
                                        <?= $this->formText($filterForm->get('number')) ?>
                                    </div>
                                    <div class="col-md-8">
                                        <?= $this->formSelect($filterForm->get('carrier')) ?>
                                    </div>
                                </div>
                            </td>
                            <td><?= $this->formSelect($filterForm->get('status')) ?></td>
                            <td>&nbsp;</td>
                            <td><?= $this->formText($filterForm->get('loading_date')) ?></td>
                            <td><?= $this->formText($filterForm->get('unloading_date')) ?></td>
                            <td class="text-right">
                                <div class="btn-group">
                                    <a class="btn btn-primary" href="<?= $this->url('dashboard/purchaseContract/advanced', [
                                        'id'      => $this->contract->getContractId(),
                                        'company' => $company->getContractorId()]) ?>"><i class="fa fa-refresh"></i></a>
                                    <button class="btn btn-primary" form="wagon-filter"><i class="fa fa-search"></i></button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th>&nbsp;</th>
                            <th><?= sprintf('Всего вагонов: %d', $this->wagons->count()) ?></th>
                            <th>&nbsp;</th>
                            <th class="text-right">
                                <?= $this->currencyFormat($this->wagons->getTotalMaterialPrice() + $this->wagons->getTotalDeliveryPrice(), 'UAH') ?>
                                <div class="hint"><?= sprintf('%s / %s',
                                        $this->currencyFormat($this->wagons->getTotalMaterialPrice(), 'UAH'),
                                        $this->currencyFormat($this->wagons->getTotalDeliveryPrice(), 'UAH')) ?>
                                </div>
                            </th>
                            <th class="text-right"><?= $this->numberFormat($this->wagons->getTotalLoadingWeight(),
                                    NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, null, 3,
                                    [NumberFormatter::POSITIVE_SUFFIX => sprintf(' %s.', $this->translate('tons'))]) ?></th>
                            <th class="text-right"><?= $this->numberFormat($this->wagons->getTotalUnloadingWeight(),
                                    NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, null, 3,
                                    [NumberFormatter::POSITIVE_SUFFIX => sprintf(' %s.', $this->translate('tons'))]) ?></th>
                            <th>&nbsp;</th>
                        </tr>
                        </thead>
                        <?= $this->placeholder('table_body') ?>
                        <tfoot>
                        <tr>
                            <th>&nbsp;</th>
                            <th><?= sprintf('Всего вагонов: %d', $this->wagons->count()) ?></th>
                            <th>&nbsp;</th>
                            <th class="text-right">
                                <?= $this->currencyFormat($this->wagons->getTotalMaterialPrice() + $this->wagons->getTotalDeliveryPrice(), 'UAH') ?>
                                <div class="hint"><?= sprintf('%s / %s',
                                        $this->currencyFormat($this->wagons->getTotalMaterialPrice(), 'UAH'),
                                        $this->currencyFormat($this->wagons->getTotalDeliveryPrice(), 'UAH')) ?></div>
                            </th>
                            <th class="text-right"><?= $this->numberFormat($this->wagons->getTotalLoadingWeight(),
                                    NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, null, 3,
                                    [NumberFormatter::POSITIVE_SUFFIX => sprintf(' %s.', $this->translate('tons'))]) ?></th>
                            <th class="text-right"><?= $this->numberFormat($this->wagons->getTotalUnloadingWeight(),
                                    NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, null, 3,
                                    [NumberFormatter::POSITIVE_SUFFIX => sprintf(' %s.', $this->translate('tons'))]) ?></th>
                            <th>&nbsp;</th>
                        </tr>
                        </tfoot>
                    </table>
                    <?php if (!$this->wagons || !$this->wagons->count()): ?>
                        <div class="text-center">
                            <br><br>
                            <img src="<?= $this->basePath('img/empty.svg') ?>" alt="Empty folder" style="max-width:200px">
                            <h3><?= $this->translate('No wagons') ?></h3>
                            <p><?= $this->translate('Do you want to add a new wagon?') ?></p>
                            <a href="<?= $this->url('dashboard/purchaseWagon/loading', [
                                'company'  => $company->getContractorId(),
                                'contract' => $this->contract->getContractId()]) ?>"
                               class="btn btn-success">
                                <i class="fa fa-plus-circle fa-fw"></i>
                                <?= $this->translate('Add new wagon') ?>
                            </a>
                            <br><br>
                        </div>
                    <?php endif ?>
                </div>
            </div>
        </div>
        <div class="col-md-4" style="max-width:480px">
            <div class="panel">
                <div class="panel-header">
                    <div class="panel-title">
                        <i class="fa fa-info-circle fa-fw text-sub"></i>
                        <?= $this->translate('Contract information') ?>
                    </div>
                </div>
                <div class="panel-body">
                    <?= $this->partial('dashboard/purchase-contract/contract', ['contract' => $this->contract]); ?>
                </div>
            </div>
        </div>
    </div>
<?php
$this->headLink()->appendStylesheet('/css/datepicker.min.css');
$this->inlineScript()->appendFile($this->basePath('/js/vendor/datepicker.min.js'));
$this->headLink()->appendStylesheet($this->basePath('css/dropdown.css'));
$this->inlineScript()->appendFile($this->basePath('js/dropdown.min.js'));
$this->headLink()->appendStylesheet($this->basePath('/css/modal.css'));
$this->inlineScript()->appendFile($this->basePath('/js/modal.js'));
$this->inlineScript()->captureStart();
echo /** @lang JavaScript */
<<<JS
$('.dropdown').dropdown();

$(document).ready(function () {

    $('#wagon-filter').on('submit', function (e) {
        e.preventDefault();
        window.location.search = '?' + $(':input[form=wagon-filter]').filter(function () {
            return $.trim(this.value).length > 0
        }).serialize();
    });

});

var unloadSelDate = $('#unload-date');
loadDateInput = $('input[name=loading_date]'),
    unloadDateInput = $('input[name=unloading_date]');

unloadSelDate.datepicker({dateFormat: 'dd.mm.yyyy'});

loadDateInput.datepicker({
    dateFormat: 'yyyy-mm-dd',
    minDate: new Date(loadDateInput.data('date-min')),
    maxDate: new Date(loadDateInput.data('date-max')),
    multipleDatesSeparator: ' - ',
    range: true,
    dateFormat: 'dd.mm.yyyy',
    onSelect: function (formattedDate, date, inst) {
        //inst.hide();
    }
});

unloadDateInput.datepicker({
    dateFormat: 'yyyy-mm-dd',
    minDate: new Date(unloadDateInput.data('date-min')),
    maxDate: new Date(unloadDateInput.data('date-max')),
    dateFormat: 'dd.mm.yyyy',
    multipleDatesSeparator: ' - ',
    range: true,
    onSelect: function (formattedDate, date, inst) {
        //inst.hide();
    }
});

$.modalConfig({
    title: '{$this->translate('Confirmation of deletion')}',
    message: '{$this->translate('Are you sure you want to delete this entry?')}',
    cancelText: '{$this->translate('Cancel')}',
    confirmText: '{$this->translate('Confirm')}'
});

var buttonSelected = $('#unload-selected').attr('disabled', true),
    wagonAll = $('input[name=wagon_all]'),
    wagonIds = $('input[type=checkbox][name^="wagon["]');

wagonAll.on('click', function () {
    wagonIds.prop('checked', $(this).prop('checked')).trigger('change');
});

wagonIds.on('change', function () {
    $('#delete-selected').attr('disabled', !wagonIds.filter(':checked').length);
    buttonSelected.attr('disabled', !wagonIds.filter(':checked').length);
});


$('#delete-selected').attr('disabled', true).modal({
    onConfirm: function (element) {
        if ('delete-selected' === element.attr('id') && 'disabled' !== element.attr('disabled')) {
            var ids = wagonIds.filter(':checked').map(function () {
                return $(this).data('id');
            }).toArray().join(',');
            window.location = $('#delete-selected').attr('href') + '?ids=' + ids;
        } else {
            var href = element.attr('href');
            if (href !== undefined && href.length) {
                window.location.href = href;
            }
        }
    }
});

buttonSelected.on('click', function (e) {
    e.preventDefault();
    if ('disabled' !== $(this).attr('disabled')) {
        var ids = wagonIds.filter(':checked').map(function () {
            return $(this).data('id');
        }).toArray().join(',');
        window.location = $(this).attr('href') + '?date=' + unloadSelDate.val() + '&ids=' + ids;
    }
});

JS;
echo $this->inlineScript()->captureEnd();