<?php
/**
 * @var \Contractor\Entity\ContractorCompany $company
 */
?>
<div class="layout-toolbar">
    <div class="row middle-md">
        <div class="col-md">
            <h1><i class="fa fa-dashboard fa-fw"></i>
                <?= $title = sprintf('%s: %s - %s', $this->translate('Dashboard'), $company->getContractorName(), $this->translate('Editing of purchase contract data')) ?>
            </h1>
            <div class="hint"><?= $company->getContractorType() ?></div>
            <?php echo $this->headTitle($title) ?>
        </div>
        <div class="col-md end-md">
            <?= $this->partial('partial/dashboard-menu', ['company' => $company]) ?>
        </div>
    </div>
</div>


<?php
/**
 * @var \Zend\Form\Element\Collection $collection
 * @var \Zend\Form\Form $form
 * @var \Zend\Form\Fieldset $fieldset
 */
$form->setAttribute('action', $this->url('dashboard/purchaseContract/edit', ['company' => $company->getContractorId()]));
$form->prepare();
echo $this->form()->openTag($form) ?>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

<div class="panel">
    <div class="panel-header">
        <div class="panel-title">
            <i class="fa fa-tag fa-fw"></i>
            <?= $this->translate('Common data') ?>
        </div>
    </div>
    <div class="panel-body">
        <?= $this->formHidden($form->get('csrf')) ?>
        <?= $this->formHidden($form->get('contract_id')) ?>

        <div class="form-row">
            <?= $this->formLabel($form->get('contract_number')) ?>
            <?= $this->formText($form->get('contract_number')) ?>
            <?= $this->formElementErrors($form->get('contract_number')) ?>
        </div>

        <div class="form-row" style="display:none">
            <?= $this->formLabel($form->get('company_id')) ?>
            <?= $this->formSelect($form->get('company_id')) ?>
            <?= $this->formElementErrors($form->get('company_id')) ?>
        </div>

        <div class="form-row" style="display:none">
            <?= $this->formLabel($form->get('warehouse_id')) ?>
            <?= $this->formSelect($form->get('warehouse_id')) ?>
            <?= $this->formElementErrors($form->get('warehouse_id')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('material_id')) ?>
            <?= $this->formSelect($form->get('material_id')) ?>
            <?= $this->formElementErrors($form->get('material_id')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('provider_id')) ?>
            <?= $this->formSelect($form->get('provider_id')) ?>
            <?= $this->formElementErrors($form->get('provider_id')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('carrier_type')) ?>
            <?= $this->formSelect($form->get('carrier_type')) ?>
            <?= $this->formElementErrors($form->get('carrier_type')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('conditions')) ?>
            <?= $this->formSelect($form->get('conditions')) ?>
            <?= $this->formElementErrors($form->get('conditions')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('country')) ?>
            <?= $this->formSelect($form->get('country')) ?>
            <?= $this->formElementErrors($form->get('country')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('station_id')) ?>
            <?= $this->formSelect($form->get('station_id')) ?>
            <?= $this->formElementErrors($form->get('station_id')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('created')) ?>
            <?= $this->formText($form->get('created')) ?>
            <?= $this->formElementErrors($form->get('created')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('price')) ?>
            <?= $this->formNumber($form->get('price')) ?>
            <?= $this->formElementErrors($form->get('price')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('tax')) ?>
            <?= $this->formNumber($form->get('tax')) ?>
            <?= $this->formElementErrors($form->get('tax')) ?>
        </div>

        <?= $this->formSubmit($form->get('save_and_remain')) ?>
        <?= $this->formSubmit($form->get('save_and_exit')) ?>
        <a href="<?= $this->url('dashboard/purchaseContract', ['company' => $company->getContractorId()]) ?>" class="btn btn-danger">
            <i class="fa fa-close fa-fw"></i>
            <?= $this->translate('Cancel') ?>
        </a>

    </div>
</div>

<?= $this->form()->closeTag() ?>

<?php
$this->headLink()->appendStylesheet('/css/datepicker.min.css');
$this->inlineScript()->appendFile($this->basePath('/js/vendor/datepicker.min.js'));
$this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function () {

    var countrySel = $('select[name=country]'),
        stationSel = $('select[name=station_id]');

    var filterStation = function (r) {
        var countryIso = countrySel.val();
        if (countryIso.length) {
            stationSel.find('option').show().not('[data-country=' + countryIso + ']').hide();
            if (true === r) {
                stationSel.val(0);
            }
        }
    };
    
    countrySel.on('change', function() {
      filterStation(true);
    });
    
    filterStation();


    $('input[name=created]').datepicker({
        maxDate: new Date(),
        onSelect: function (formattedDate, date, inst) {
            inst.hide();
        }
    });

    let companySelect = $('select[name=company_id]'),
        warehouseSelect = $('select[name=warehouse_id]');
    companySelect.on('change', function () {
        let plantId = $(this).find('option:selected').data('plant');
        let options = warehouseSelect.find('option').hide();
        options.filter('[data-plant=' + plantId + '][data-type=materialWarehouse]').show().get(0).selected = true;
    });
    let plantId = companySelect.find('option:selected').data('plant');
    warehouseSelect.find('option').hide().filter('[data-plant=' + plantId + '][data-type=materialWarehouse]').show().get(0).selected = true;
});
JS;
$this->inlineScript()->captureEnd() ?>
