<?php
/**
 * @var \Contractor\Entity\ContractorCompany $company
 */
?>
    <div class="layout-toolbar">
        <div class="row middle-md">
            <div class="col-md">
                <h1><i class="fa fa-download fa-fw"></i>
                    <?= $title = sprintf('%s - %s', $this->translate('Purchase contracts'), $company->getContractorName()) ?></h1>
                <?php echo $this->headTitle($title) ?>
            </div>
            <div class="col-md end-md">
                <?= $this->partial('partial/dashboard-menu', ['company' => $company]) ?>
            </div>
        </div>
    </div>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

<?php /** @var \Zend\Paginator\Paginator $paginator */ ?>
<?php if ($paginator->count()): ?>

    <div class="panel">
        <div class="panel-header">
            <div class="row middle-md">
                <div class="col-md">
                    <div class="panel-title">
                        <i class="fa fa-navicon fa-fw"></i>
                        <?= $title = $this->translate('Purchase contracts') ?>
                    </div>
                </div>
                <div class="col-md end-md">
                    <a href="<?= $this->url('dashboard/purchaseContract/edit', ['company' => $company->getContractorId()]) ?>"
                       class="btn btn-primary btn-sm">
                        <i class="fa fa-plus-circle fa-fw"></i>
                        <?= $this->translate('Add new contract') ?>
                    </a>
                    &nbsp;
                    <?= $this->paginationControl($this->paginator, 'Sliding', 'partial/paginator', [
                        'route'  => 'dashboard/purchaseContract',
                        'params' => ['company' => $company->getContractorId()]]) ?>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <table class="table-data table-hover">
                <thead>
                <tr>
                    <th class="text-center" style="width:32px"><?= $this->translate('Flag') ?></th>
                    <th class="text-left" style="width:15rem"><?= sprintf('%s / %s', $this->translate('Contract number'), $this->translate('Material')) ?></th>
                    <th class="text-left"><?= $this->translate('Provider') ?></th>
                    <th class="text-center" style="width:6rem"><?= $this->translate('Carrier') ?></th>
                    <th class="text-left" style="width:20rem"><?= $this->translate('Conditions of delivery') ?></th>
                    <th class="text-right" style="width:72px;"><?= $this->translate('Wagons') ?></th>
                    <th class="text-right"><?= $this->translate('Price') ?></th>
                    <th class="text-right" style="width:10rem"><?= $this->translate('Updated') ?></th>
                    <th class="text-right" style="width:10rem"><?= $this->translate('Created') ?></th>
                    <th class="text-right" style="width:48px"><?= $this->translate('Tools') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var \Document\Domain\PurchaseContractEntity $contract */ ?>
                <?php foreach ($this->paginator as $contract): ?>
                    <tr data-url="<?= $this->url('dashboard/purchaseContract/advanced', ['company' => $company->getContractorId(), 'id' => $contract->getContractId()]) ?>">
                        <td class="text-center">
                            <img class="flag-icon" src="<?= $this->basePath(sprintf('/img/flags/%s.png', $contract->getCountry())) ?>"
                                 alt="<?= $contract->getCountry() ?>"></td>
                        <td class="text-left">
                            <?= $contract->getMaterialName() ?>
                            <div class="hint"><?= $contract->getContractNumber() ?></div>
                        </td>
                        <td class="text-left">
                            <?= $contract->getProviderName() ?>
                        </td>
                        <td class="text-center">
                            <?php if ('train' == $contract->getCarrierType()): ?>
                                <i class="fa fa-train" title="<?= $this->translate('Railway transport') ?>"></i>
                            <?php elseif ('truck' == $contract->getCarrierType()): ?>
                                <i class="fa fa-truck" title="<?= $this->translate('Motor transport') ?>"></i>
                            <?php endif ?>
                        </td>
                        <td class="text-left">
                            <?php if (\Document\Domain\PurchaseContractEntity::CONDITIONS_TYPE_FCA == $contract->getConditions()): ?>
                                <?= $this->translate('FCA') ?>
                                <div class="hint"><?= $this->translate('Free Carrier') ?></div>
                            <?php elseif (\Document\Domain\PurchaseContractEntity::CONDITIONS_TYPE_CPT == $contract->getConditions()): ?>
                                <?= $this->translate('CPT') ?>
                                <div class="hint"><?= $this->translate('Carriage Paid To') ?></div>
                            <?php elseif (\Document\Domain\PurchaseContractEntity::CONDITIONS_TYPE_CPT_RETURN == $contract->getConditions()): ?>
                                <?= $this->translate('CPT(r)') ?>
                                <div class="hint"><?= $this->translate('Carriage Paid To and Return') ?></div>
                            <?php endif ?>
                        </td>
                        <td class="text-right">
                            <?= sprintf('%s: %s', $this->translate('Loaded'), $contract->getLoadedWagons()) ?>
                            <div class="hint"><?= sprintf('%s: %s', $this->translate('Unloaded'), $contract->getUnloadedWagons()) ?></div>
                        </td>
                        <td class="text-right">
                            <?= $this->currencyFormat($contract->getPrice(), 'UAH') ?>
                            <div class="hint">
                                <i class="fa fa-info-circle" title="<?= $this->translate('Price with VAT') ?>"></i>
                                <?= $this->currencyFormat($contract->getPrice(true), 'UAH') ?>
                            </div>
                        </td>
                        <td class="text-right"><?= $this->dateFormat($contract->getUpdated(), IntlDateFormatter::LONG) ?>
                            <div class="hint"><?= $this->dateFormat($contract->getUpdated(), IntlDateFormatter::NONE, IntlDateFormatter::LONG) ?></div>
                        </td>
                        <td class="text-right"><?= $this->dateFormat($contract->getCreated(), IntlDateFormatter::LONG) ?>
                            <div class="hint"><?= $this->dateFormat($contract->getCreated(), IntlDateFormatter::NONE, IntlDateFormatter::LONG) ?></div>
                        </td>
                        <td class="text-right">
                            <div class="dropdown">
                                <button class="dropdown-toggle btn btn-default"><i class="fa fa-navicon"></i></button>
                                <ul class="dropdown-list">
                                    <li>
                                        <a href="<?= $this->url('dashboard/purchaseContract/advanced', [
                                            'company' => $company->getContractorId(),
                                            'id'      => $contract->getContractId()]) ?>">
                                            <i class="fa fa-eye fa-fw"></i>
                                            <?= $this->translate('Show contract') ?>
                                        </a>
                                    </li>
                                    <li>
                                        <?php if (!$contract->getLoadedWagons() && !$contract->getUnloadedWagons()): ?>
                                        <a href="<?= $this->url('dashboard/purchaseContract/edit', ['company' => $company->getContractorId(), 'id' => $contract->getContractId()]) ?>">
                                            <i class="fa fa-pencil fa-fw"></i>
                                            <?= $this->translate('Edit contract') ?>
                                        </a>
                                        <?php else: ?>
                                            <span class="disabled">
                                                <i class="fa fa-pencil fa-fw"></i>
                                                <?= $this->translate('Edit contract') ?>
                                            </span>
                                        <?php endif ?>
                                    </li>
                                    <li class="dropdown-list-separator"></li>
                                    <li>
                                        <?php if (!$contract->getLoadedWagons() && !$contract->getUnloadedWagons()): ?>
                                        <a href="<?= $this->url('dashboard/purchaseContract/delete', ['company' => $company->getContractorId(), 'id' => $contract->getContractId()]) ?>"
                                           data-modal="confirm">
                                            <i class="fa fa-trash fa-fw"></i>
                                            <?= $this->translate('Delete contract') ?>
                                        </a>
                                        <?php else: ?>
                                            <span class="disabled">
                                                <i class="fa fa-trash fa-fw"></i>
                                                <?= $this->translate('Delete contract') ?>
                                            </span>
                                        <?php endif ?>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>

<?php else: ?>
    <div class="layout-not-found">
        <h3><?= $this->translate('No contracts') ?></h3>
        <p><?= $this->translate('Do you want to add a new contract?') ?></p>
        <a href="<?= $this->url('dashboard/purchaseContract/edit', [
            'company' => $company->getContractorId()]) ?>" class="btn btn-lg btn-success">
            <i class="fa fa-plus-circle fa-fw"></i>
            <?= $this->translate('Add new contract') ?>
        </a>
    </div>
<?php endif ?>

<?php
$this->headLink()->appendStylesheet($this->basePath('css/dropdown.css'));
$this->inlineScript()->appendFile($this->basePath('js/dropdown.min.js'));
$this->headLink()->appendStylesheet($this->basePath('/css/modal.css'));
$this->inlineScript()->appendFile($this->basePath('/js/modal.js'));
$this->inlineScript()->captureStart();
echo /** @lang JavaScript */
<<<JS
$('.dropdown').dropdown();
$.modalConfig({
    title      : '{$this->translate('Confirmation of deletion')}',
    message    : '{$this->translate('Are you sure you want to delete this entry?')}',
    cancelText : '{$this->translate('Cancel')}',
    confirmText: '{$this->translate('Confirm')}'
});
$('.table-hover tr[data-url] td:not(:last-child)').on('click', function(e) {
  e.preventDefault();
  window.location = $(this).closest('tr').data('url');
});
JS;
echo $this->inlineScript()->captureEnd();