<?php
/**
 * @var \Zend\Form\Element\Collection $collection
 * @var \Zend\Form\Form $form
 * @var \Zend\Form\Fieldset $fieldset
 */
?>

    <div class="layout-toolbar">
        <div class="row middle-md">
            <div class="col-md">
                <h1>
                    <i class="fa fa-pencil fa-fw"></i>
                    <?= $title = $this->translate('Manage of purchase contract') ?>
                </h1>
                <?php echo $this->headTitle($title) ?>
            </div>
            <div class="col-md end-md">
                <?php // $this->formSubmit($form->get('save_and_remain')) ?>
                <?php // $this->formSubmit($form->get('save_and_exit')) ?>
                <a href="<?= $this->url('purchaseContract') ?>" class="btn btn-danger">
                    <i class="fa fa-close fa-fw"></i>
                    <?= $this->translate('Cancel') ?>
                </a>
            </div>
        </div>
    </div>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

<?= $this->partial('document/purchase-contract/contract', ['contract' => $this->contract]); ?>

    <div class="panel">
        <div class="panel-header">
            <div class="row middle-md">
                <div class="col-md">
                    <div class="panel-title">
                        <i class="fa fa-truck fa-fw"></i>
                        <?= $this->translate('Wagons data') ?>
                    </div>
                </div>
                <div class="col-md end-md">
                    <a href="<?= $this->url('purchaseWagon/loading', ['contract' => $this->contract->getContractId()]) ?>">
                        <i class="fa fa-plus-circle fa-fw"></i>
                        <?= $this->translate('Add new wagon') ?>
                    </a>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <?php if ($this->wagons && $this->wagons->count()): ?>
                <table class="table-data">
                    <thead>
                    <tr>
                        <th class="text-left"><?= sprintf('%s / %s', $this->translate('Wagon number'), $this->translate('Carrier')) ?></th>
                        <th class="text-center" style="width:10rem"><?= $this->translate('Wagon status') ?></th>
                        <th class="text-right"><?= sprintf('%s / %s', $this->translate('Material'), $this->translate('Transport')) ?></th>
                        <th class="text-right"><?= sprintf('%s / %s', $this->translate('Loading weight'), $this->translate('date')) ?></th>
                        <th class="text-right"><?= sprintf('%s / %s', $this->translate('Unloading weight'), $this->translate('date')) ?></th>
                        <th class="text-right" style="width:4rem"><?= $this->translate('Tools') ?></th>
                    </tr>
                    </thead>
                    <?php /** @var \Document\Domain\PurchaseWagonEntity $wagon */ ?>
                    <tbody>
                    <?php foreach ($this->wagons as $wagon): ?>
                        <tr>
                            <td class="text-left">
                                <?= $wagon->getWagonNumber() ?>
                                <div class="hint"><?= $wagon->getCarrierName() ?></div>
                            </td>
                            <td class="text-center">
                                <?php if ($wagon::STATUS_LOADED == $wagon->getStatus()): ?>
                                    <div class="text-warning"><?= $this->translate('Loaded') ?></div>
                                <?php elseif ($wagon::STATUS_UNLOADED == $wagon->getStatus()): ?>
                                    <div class="text-success"><?= $this->translate('Unloaded') ?></div>
                                <?php else: ?>
                                    <div class="text-error"><?= $this->translate('Status not defined') ?></div>
                                <?php endif ?>
                            </td>
                            <td class="text-right">
                                <?= $this->currencyFormat($wagon->getMaterialPrice(), 'UAH') ?>
                                <div class="hint"><?= $this->currencyFormat($wagon->getDeliveryPrice(), 'UAH') ?></div>
                                <?php if (0 < $wagon->getTransportPrice()): ?>
                                    <div class="hint">
                                        <i class="fa fa-info-circle fa-fw"
                                           title="<?= $wagon->getTransportComment() ?>"></i>
                                        <?= $this->currencyFormat($wagon->getTransportPrice()) ?>
                                    </div>
                                <?php endif ?>
                            </td>
                            <td class="text-right">
                                <?= $this->numberFormat($wagon->getLoadingWeight(), NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, null, 3, [
                                    NumberFormatter::POSITIVE_SUFFIX => sprintf(' %s.', $this->translate('tons'))]) ?>
                                <div class="hint"><?= $this->dateFormat($wagon->getLoadingDate(), IntlDateFormatter::MEDIUM) ?></div>
                            </td>
                            <td class="text-right">
                                <?php if ($wagon->getUnloadingDate() && $wagon->getUnloadingWeight()): ?>
                                    <?= $this->numberFormat($wagon->getUnloadingWeight(), NumberFormatter::DECIMAL, NumberFormatter::TYPE_DEFAULT, null, 3, [
                                        NumberFormatter::POSITIVE_SUFFIX => sprintf(' %s.', $this->translate('tons'))]) ?>
                                    <div class="hint"><?= $this->dateFormat($wagon->getUnloadingDate(), IntlDateFormatter::MEDIUM) ?></div>
                                <?php else: ?>
                                    <div class="hint"><?= $this->translate('No specified') ?></div>
                                <?php endif ?>
                            </td>
                            <td class="text-right">
                                <div class="dropdown">
                                    <button class="dropdown-toggle btn btn-default"><i class="fa fa-navicon"></i>
                                    </button>
                                    <ul class="dropdown-list">
                                        <li>
                                            <a href="<?= $this->url('purchaseWagon/unloading', ['contract' => $wagon->getContractId(), 'id' => $wagon->getWagonId()]) ?>">
                                                <i class="fa fa-upload fa-fw"></i>
                                                <?= $this->translate('Unloading wagon') ?>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="<?= $this->url('purchaseWagon/edit', ['contract' => $wagon->getContractId(), 'id' => $wagon->getWagonId()]) ?>">
                                                <i class="fa fa-pencil fa-fw"></i>
                                                <?= $this->translate('Edit wagon') ?>
                                            </a>
                                        </li>
                                        <li class="dropdown-list-separator"></li>
                                        <li>
                                            <a data-modal="confirm"
                                               href="<?= $this->url('purchaseWagon/delete', ['contract' => $wagon->getContractId(), 'id' => $wagon->getWagonId()]) ?>">
                                                <i class="fa fa-trash fa-fw"></i>
                                                <?= $this->translate('Delete wagon') ?>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach ?>
                    </tbody>
                </table>
            <?php else: ?>
                <div class="text-center">
                    <br><br>
                    <img src="<?= $this->basePath('img/empty.svg') ?>" alt="Empty folder" style="max-width:200px">
                    <h3><?= $this->translate('No wagons') ?></h3>
                    <p><?= $this->translate('Do you want to add a new wagon?') ?></p>
                    <a href="<?= $this->url('purchaseWagon/edit', ['contract' => $this->contract->getContractId()]) ?>"
                       class="btn btn-success">
                        <i class="fa fa-plus-circle fa-fw"></i>
                        <?= $this->translate('Add new wagon') ?>
                    </a>
                    <br><br>
                </div>
            <?php endif ?>
        </div>
    </div>

<?php
$this->headLink()->appendStylesheet($this->basePath('css/dropdown.css'));
$this->inlineScript()->appendFile($this->basePath('js/dropdown.min.js'));
$this->headLink()->appendStylesheet($this->basePath('/css/modal.css'));
$this->inlineScript()->appendFile($this->basePath('/js/modal.js'));
$this->inlineScript()->captureStart();
echo /** @lang JavaScript */
<<<JS
$('.dropdown').dropdown();
$.modalConfig({
    title      : '{$this->translate('Confirmation of deletion')}',
    message    : '{$this->translate('Are you sure you want to delete this entry?')}',
    cancelText : '{$this->translate('Cancel')}',
    confirmText: '{$this->translate('Confirm')}'
});
JS;
echo $this->inlineScript()->captureEnd();