<?php
/**
 * @var \Zend\Form\Element\Collection $collection
 * @var \Zend\Form\Form $form
 * @var \Zend\Form\Fieldset $fieldset
 */
$form->setAttribute('action', $this->url('purchaseContract/edit'));
$form->prepare();
echo $this->form()->openTag($form) ?>

<div class="layout-toolbar">
    <div class="row middle-md">
        <div class="col-md">
            <h1>
                <i class="fa fa-pencil fa-fw"></i>
                <?= $title = $this->translate('Editing of purchase contract data') ?>
            </h1>
            <?php echo $this->headTitle($title) ?>
        </div>
        <div class="col-md end-md">
            <?= $this->formSubmit($form->get('save_and_remain')) ?>
            <?= $this->formSubmit($form->get('save_and_exit')) ?>
            <a href="<?= $this->url('purchaseContract') ?>" class="btn btn-danger">
                <i class="fa fa-close fa-fw"></i>
                <?= $this->translate('Cancel') ?>
            </a>
        </div>
    </div>
</div>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

<div class="panel">
    <div class="panel-header">
        <div class="panel-title">
            <i class="fa fa-tag fa-fw"></i>
            <?= $this->translate('Common data') ?>
        </div>
    </div>
    <div class="panel-body">
        <?= $this->formHidden($form->get('csrf')) ?>
        <?= $this->formHidden($form->get('contract_id')) ?>

        <div class="form-row">
            <?= $this->formLabel($form->get('contract_number')) ?>
            <?= $this->formText($form->get('contract_number')) ?>
            <?= $this->formElementErrors($form->get('contract_number')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('company_id')) ?>
            <?= $this->formSelect($form->get('company_id')) ?>
            <?= $this->formElementErrors($form->get('company_id')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('warehouse_id')) ?>
            <?= $this->formSelect($form->get('warehouse_id')) ?>
            <?= $this->formElementErrors($form->get('warehouse_id')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('material_id')) ?>
            <?= $this->formSelect($form->get('material_id')) ?>
            <?= $this->formElementErrors($form->get('material_id')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('provider_id')) ?>
            <?= $this->formSelect($form->get('provider_id')) ?>
            <?= $this->formElementErrors($form->get('provider_id')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('carrier_type')) ?>
            <?= $this->formSelect($form->get('carrier_type')) ?>
            <?= $this->formElementErrors($form->get('carrier_type')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('conditions')) ?>
            <?= $this->formSelect($form->get('conditions')) ?>
            <?= $this->formElementErrors($form->get('conditions')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('country')) ?>
            <?= $this->formSelect($form->get('country')) ?>
            <?= $this->formElementErrors($form->get('country')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('created')) ?>
            <?= $this->formText($form->get('created')) ?>
            <?= $this->formElementErrors($form->get('created')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('price')) ?>
            <?= $this->formNumber($form->get('price')) ?>
            <?= $this->formElementErrors($form->get('price')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('tax')) ?>
            <?= $this->formNumber($form->get('tax')) ?>
            <?= $this->formElementErrors($form->get('tax')) ?>
        </div>

    </div>
</div>

<?= $this->form()->closeTag() ?>

<?php
$this->headLink()->appendStylesheet('/css/datepicker.min.css');
$this->inlineScript()->appendFile($this->basePath('/js/vendor/datepicker.min.js'));
$this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function () {
    
    $('input[name=created]').datepicker({
        maxDate : new Date(),
        onSelect: function (formattedDate, date, inst) {
            inst.hide();
        }
    });
    
    let companySelect   = $('select[name=company_id]'),
        warehouseSelect = $('select[name=warehouse_id]');
    companySelect.on('change', function () {
        let plantId = $(this).find('option:selected').data('plant');
        let options = warehouseSelect.find('option').hide();
        options.filter('[data-plant=' + plantId + ']').show();
    });
});
JS;
$this->inlineScript()->captureEnd() ?>
