<?php
/**
 * @var \Zend\Form\Element\Collection $collection
 * @var \Zend\Form\Form $form
 * @var \Zend\Form\Fieldset $fieldset
 */
$form->setAttribute('action', $this->url('material/edit'));
$form->prepare();
echo $this->form()->openTag($form) ?>

<div class="layout-toolbar">
    <div class="row middle-md">
        <div class="col-md">
            <h1>
                <i class="fa fa-pencil fa-fw"></i>
                <?= $title = $this->translate('Editing of material data') ?>
            </h1>
            <?php echo $this->headTitle($title) ?>
        </div>
        <div class="col-md end-md">
            <?= $this->formSubmit($form->get('save_and_remain')) ?>
            <?= $this->formSubmit($form->get('save_and_exit')) ?>
            <a href="<?= $this->url('material') ?>" class="btn btn-danger">
                <i class="fa fa-close fa-fw"></i>
                <?= $this->translate('Cancel') ?>
            </a>
        </div>
    </div>
</div>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

<div class="panel">
    <div class="panel-header">
        <div class="panel-title">
            <i class="fa fa-tag fa-fw"></i>
            <?= $this->translate('Common data') ?>
        </div>
    </div>
    <div class="panel-body">
        <?= $this->formHidden($form->get('csrf')) ?>
        <?= $this->formHidden($form->get('material_id')) ?>
        <div class="form-row">
            <?= $this->formLabel($form->get('material_name')) ?>
            <?= $this->formText($form->get('material_name')) ?>
            <?= $this->formElementErrors($form->get('material_name')) ?>
        </div>

        <div class="form-row">
            <?= $this->formLabel($form->get('description')) ?>
            <?= $this->formTextarea($form->get('description')) ?>
            <?= $this->formElementErrors($form->get('description')) ?>
        </div>

        <fieldset class="fieldset">
            <legend class="fieldset-toggle"><?= $this->translate($form->get('fraction')->getLabel()) ?></legend>
            <!-- Fraction fieldset begin -->
            <div class="fieldset-body">
                <div class="row">
                    <?php $fieldset = $form->get('fraction') ?>
                    <div class="col-md">
                        <div class="form-row">
                            <?= $this->formNumber($fieldset->get('min_size')) ?>
                            <?= $this->formElementErrors($fieldset->get('min_size')) ?>
                        </div>
                    </div>
                    <div class="col-md">
                        <div class="form-row">
                            <?= $this->formNumber($fieldset->get('max_size')) ?>
                            <?= $this->formElementErrors($fieldset->get('max_size')) ?>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Fraction fieldset end -->
        </fieldset>

    </div>
</div>

<?= $this->form()->closeTag() ?>

<?php
$this->inlineScript()->captureStart();
echo /** @lang JavaScript */
<<<JS
var fset = $('.fieldset'),
    body = fset.find('.fieldset-body'),
    show = !!body.find('input').filter(function () {
        return !!this.value && parseInt(this.value) !== 0;
    }).length || !!body.find('.form-errors').length;
show && fset.attr('aria-expanded', 'true') || fset.attr('aria-expanded', 'false') && body.hide();
fset.on('click', '.fieldset-toggle', function () {
    fset.attr('aria-expanded') === 'true' &&
    body.slideUp() && fset.attr('aria-expanded', 'false') ||
    body.slideDown() && fset.attr('aria-expanded', 'true');
});
JS;
$this->inlineScript()->captureEnd() ?>
