<div class="layout-toolbar">
    <div class="row middle-md">
        <div class="col-md">
            <h1>
                <i class="fa fa-star-o fa-fw"></i>
                <?= $title = $this->translate('Materials') ?>
            </h1>
            <?php echo $this->headTitle($title) ?>
        </div>
        <div class="col-md end-md">
            <a href="<?= $this->url('material/edit') ?>" class="btn btn-primary">
                <i class="fa fa-plus-circle fa-fw"></i>
                <?= $this->translate('Add new material') ?>
            </a>
        </div>
    </div>
</div>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

<?php /** @var \Zend\Paginator\Paginator $paginator */ ?>
<?php if ($paginator->count()): ?>

    <div class="panel">
        <div class="panel-header">
            <div class="row middle-md">
                <div class="col-md">
                    <div class="panel-title">
                        <i class="fa fa-navicon fa-fw"></i>
                        <?= $this->translate('Material list') ?>
                    </div>
                </div>
                <div class="col-md end-md">
                    <?= $this->paginationControl($this->paginator, 'Sliding', 'partial/paginator', ['route' => 'material']) ?>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <table class="table-data">
                <thead>
                <tr>
                    <th class="text-left"><?= $this->translate('Material name') ?></th>
                    <th class="text-right" style="width:130px"><?= $this->translate('Updated') ?></th>
                    <th class="text-right" style="width:130px"><?= $this->translate('Created') ?></th>
                    <th class="text-right" style="width:48px"><?= $this->translate('Tools') ?></th>
                </tr>
                </thead>
                <tbody>
                <?php /** @var \Resource\Domain\MaterialEntity $material */ ?>
                <?php foreach ($this->paginator as $material): ?>
                    <tr>
                        <td class="text-left">
                            <a href="<?= $this->url('material/edit', ['id' => $material->getMaterialId()]) ?>"><?= $material->getMaterialName() ?></a>
                            <?php if ($fraction = trim($material->getFraction()->toString())): ?>
                                <div class="hint">
                                    <i class="fa fa-flask fa-fw"></i>
                                    <?= $fraction ?>
                                </div>
                            <?php endif ?>
                        </td>
                        <td class="text-right"><?= $this->dateFormat($material->getUpdated(), IntlDateFormatter::LONG) ?>
                            <div class="hint"><?= $this->dateFormat($material->getUpdated(), IntlDateFormatter::NONE, IntlDateFormatter::LONG) ?></div>
                        </td>
                        <td class="text-right"><?= $this->dateFormat($material->getCreated(), IntlDateFormatter::LONG) ?>
                            <div class="hint"><?= $this->dateFormat($material->getCreated(), IntlDateFormatter::NONE, IntlDateFormatter::LONG) ?></div>
                        </td>
                        <td class="text-right">
                            <div class="dropdown">
                                <button class="dropdown-toggle btn btn-default"><i class="fa fa-navicon"></i></button>
                                <ul class="dropdown-list">
                                    <li>
                                        <a href="<?= $this->url('material/edit', ['id' => $material->getMaterialId()]) ?>">
                                            <i class="fa fa-pencil fa-fw"></i>
                                            <?= $this->translate('Edit material') ?>
                                        </a>
                                    </li>
                                    <li class="dropdown-list-separator"></li>
                                    <li>
                                        <a href="<?= $this->url('material/delete', ['id' => $material->getMaterialId()]) ?>"
                                           data-modal="confirm"><i class="fa fa-trash fa-fw"></i>
                                            <?= $this->translate('Delete material') ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </td>
                    </tr>
                <?php endforeach ?>
                </tbody>
            </table>
        </div>
    </div>

<?php else: ?>
    <div class="layout-not-found">
        <h3><?= $this->translate('No countries') ?></h3>
        <p><?= $this->translate('Do you want to add a new material?') ?></p>
        <a href="<?= $this->url('material/edit') ?>" class="btn btn-lg btn-success">
            <i class="fa fa-plus-circle fa-fw"></i>
            <?= $this->translate('Add new material') ?>
        </a>
    </div>
<?php endif ?>

<?php
$this->headLink()->appendStylesheet($this->basePath('css/dropdown.css'));
$this->inlineScript()->appendFile($this->basePath('js/dropdown.min.js'));
$this->headLink()->appendStylesheet($this->basePath('/css/modal.css'));
$this->inlineScript()->appendFile($this->basePath('/js/modal.js'));
$this->inlineScript()->captureStart();
echo /** @lang JavaScript */
<<<JS
$('.dropdown').dropdown();
$.modalConfig({
    title      : '{$this->translate('Confirmation of deletion')}',
    message    : '{$this->translate('Are you sure you want to delete this entry?')}',
    cancelText : '{$this->translate('Cancel')}',
    confirmText: '{$this->translate('Confirm')}'
});
JS;
$this->inlineScript()->captureEnd();