<?php
/**
 * @var \Document\Domain\SaleContractEntity $contract
 * @var \Zend\Form\Element\Collection $collection
 * @var \Zend\Form\Form $form
 * @var \Zend\Form\Fieldset $fieldset
 */
$form->setAttribute('action', $this->url('saleWagon/edit', ['contract' => $contract->getContractId()]));
$form->prepare();
echo $this->form()->openTag($form) ?>

    <div class="layout-toolbar">
        <div class="row middle-md">
            <div class="col-md">
                <h1>
                    <i class="fa fa-pencil fa-fw"></i>
                    <?= $title = $this->translate('Editing of sale wagon data') ?>
                </h1>
                <?php echo $this->headTitle($title) ?>
            </div>
            <div class="col-md end-md">
                <?= $this->formSubmit($form->get('save_and_remain')) ?>
                <?= $this->formSubmit($form->get('save_and_exit')) ?>
                <a href="<?= $this->url('saleContract') ?>" class="btn btn-danger">
                    <i class="fa fa-close fa-fw"></i>
                    <?= $this->translate('Cancel') ?>
                </a>
            </div>
        </div>
    </div>

<?= $this->partial('partial/messenger', ['messenger' => $this->messenger]); ?>

<?= $this->partial('document/sale-contract/contract', ['contract' => $this->contract]); ?>

    <div class="row">
        <div class="col-md">

            <div class="panel">
                <div class="panel-header">
                    <div class="panel-title">
                        <i class="fa fa-tag fa-fw"></i>
                        <?= $this->translate('Common data') ?>
                    </div>
                </div>
                <div class="panel-body">
                    <?= $this->formHidden($form->get('csrf')) ?>
                    <?= $this->formHidden($form->get('wagon_id')) ?>

                    <div class="form-row">
                        <?= $this->formLabel($form->get('wagon_number')) ?>
                        <?= $this->formText($form->get('wagon_number')) ?>
                        <?= $this->formElementErrors($form->get('wagon_number')) ?>
                    </div>

                    <div class="form-row">
                        <?= $this->formLabel($form->get('loading_weight')) ?>
                        <?= $this->formNumber($form->get('loading_weight')) ?>
                        <?= $this->formElementErrors($form->get('loading_weight')) ?>
                    </div>

                </div>


            </div>

        </div>
        <div class="col-md-3">

            <div class="panel">
                <div class="panel-header">
                    <div class="panel-title">
                        <i class="fa fa-info-circle fa-fw"></i>
                        <?= $this->translate('Advanced data') ?>
                    </div>
                </div>
                <div class="panel-body">

                    <div class="form-row">
                        <?= $this->formLabel($form->get('loading_date')) ?>
                        <?= $this->formText($form->get('loading_date')) ?>
                        <?= $this->formElementErrors($form->get('loading_date')) ?>
                    </div>

                    <div class="form-row">
                        <?= $this->formLabel($form->get('carrier_id')) ?>
                        <?= $this->formSelect($form->get('carrier_id')) ?>
                        <?= $this->formElementErrors($form->get('carrier_id')) ?>
                    </div>

                    <div class="form-row">
                        <?= $this->formLabel($form->get('rate_id')) ?>
                        <?= $this->formSelect($form->get('rate_id')) ?>
                        <?= $this->formElementErrors($form->get('rate_id')) ?>
                    </div>

                </div>
            </div>

        </div>
    </div>

<?= $this->form()->closeTag() ?>

<?php
$this->headLink()->appendStylesheet($this->basePath('/css/range-slider.css'));
$this->headLink()->appendStylesheet('/css/datepicker.min.css');
$this->inlineScript()->appendFile($this->basePath('/js/vendor/datepicker.min.js'));

$this->inlineScript()->captureStart();
echo <<<JS
$(document).ready(function () {

    $('input[name=loading_date]').datepicker({
        minDate : new Date({$contract->getCreated()->format('U')} * 1000),
        maxDate : new Date(),
        onSelect: function (formattedDate, date, inst) {
            inst.hide();
        }
    });

    let aSel = $('select[name=carrier_id]'),
        bSel = $('select[name=rate_id]'),
        wNum = $('input[name=loading_weight]');

    $.ajax('/carrier/value-options', {
        data      : {
            carrier_type: '{$this->contract->getCarrierType()}',
            country     : '{$this->contract->getCountry()}'
        },
        type      : 'post',
        success   : function (res) {
            aSel.empty();
            if (!res.length) return;
            $.each(res, function (key, obj) {
                $(document.createElement('option')).attr(obj.attributes).val(obj.value).text(obj.label).appendTo(aSel);
            }) && aSel.prop({
                disabled     : false,
                selectedIndex: 0
            }).val('{$form->getObject()->getCarrierId()}').change();
        },
        beforeSend: function () {
            aSel.closest('.panel-body').addClass('loading');
        },
        complete  : function () {
            setTimeout(function() {
                    aSel.closest('.panel-body').removeClass('loading');
            }, 1000);
        }
    });

    aSel.on('change', function () {
        bSel.prop('disabled', true);
        $.ajax('/rate/value-options', {
            data      : {direction: 'outgoingDirection', carrier: aSel.val()},
            type      : 'post',
            success   : function (res) {
                bSel.empty();
                if (!res.length) return;
                $.each(res, function (key, obj) {
                    $(document.createElement('option')).attr(obj.attributes).val(obj.value).text(obj.label).appendTo(bSel);
                }) && bSel.prop({
                    disabled     : false,
                    selectedIndex: 0
                }).val('{$form->getObject()->getRateId()}');
            },
            beforeSend: function () {
                aSel.closest('.panel-body').addClass('loading');
            },
            complete  : function () {
                setTimeout(function() {
                    aSel.closest('.panel-body').removeClass('loading');
                }, 1000);
            }
        });
    });

    bSel.on('change', function () {
        let weight = $(this).find('option:selected').data('weight');
        if (weight !== 0) weight = weight.split('-').map(parseFloat);
        wNum.attr({min: $.isArray(weight) ? weight[0] : weight, max: $.isArray(weight) ? weight[1] : weight});
        wNum.val($.isArray(weight) ? weight.reduce((a, b) => a + b, 0) / 2 : weight);
    });

});
JS;
$this->inlineScript()->captureEnd(); ?>